/// <mls fileReference="_102046_/l2/buildFlowFsm/web/shared/changeOrderCatalogue.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmChangeOrderCatalogueBase } from '/_102046_/l2/buildFlowFsm/web/shared/changeOrderCatalogue.js';
import type { CmdCreateChangeOrderInput, CmdCreateChangeOrderOutput, CmdDeleteChangeOrderInput, CmdDeleteChangeOrderOutput, CmdUpdateChangeOrderInput, CmdUpdateChangeOrderOutput, QryClientPickerOutput, QryListChangeOrderOutput, QryProjectPickerOutput } from '/_102046_/l2/buildFlowFsm/web/contracts/changeOrderCatalogue.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmChangeOrderCatalogueBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_qryListChangeOrderState = Assert<Assignable<typeof page.qryListChangeOrderState, "idle" | "loading" | "success" | "error">>;
type _State_qryListChangeOrderData = Assert<Assignable<typeof page.qryListChangeOrderData, unknown[] | QryListChangeOrderOutput>>;
type _State_cmdCreateChangeOrderState = Assert<Assignable<typeof page.cmdCreateChangeOrderState, "idle" | "loading" | "success" | "error">>;
type _State_cmdCreateChangeOrderClientClientId = Assert<Assignable<typeof page.cmdCreateChangeOrderClientClientId, string | CmdCreateChangeOrderInput["clientClientId"]>>;
type _State_cmdCreateChangeOrderProjectProjectId = Assert<Assignable<typeof page.cmdCreateChangeOrderProjectProjectId, string | CmdCreateChangeOrderInput["projectProjectId"]>>;
type _State_cmdCreateChangeOrderDescription = Assert<Assignable<typeof page.cmdCreateChangeOrderDescription, string | CmdCreateChangeOrderInput["description"]>>;
type _State_cmdCreateChangeOrderScopeImpact = Assert<Assignable<typeof page.cmdCreateChangeOrderScopeImpact, string | CmdCreateChangeOrderInput["scopeImpact"]>>;
type _State_cmdCreateChangeOrderScheduleImpact = Assert<Assignable<typeof page.cmdCreateChangeOrderScheduleImpact, string | CmdCreateChangeOrderInput["scheduleImpact"]>>;
type _State_cmdCreateChangeOrderChangeAmount = Assert<Assignable<typeof page.cmdCreateChangeOrderChangeAmount, string | CmdCreateChangeOrderInput["changeAmount"]>>;
type _State_cmdCreateChangeOrderOutput = Assert<Assignable<typeof page.cmdCreateChangeOrderOutput, CmdCreateChangeOrderOutput | null>>;
type _State_cmdCreateChangeOrderError = Assert<Assignable<typeof page.cmdCreateChangeOrderError, string>>;
type _State_cmdUpdateChangeOrderState = Assert<Assignable<typeof page.cmdUpdateChangeOrderState, "idle" | "loading" | "success" | "error">>;
type _State_cmdUpdateChangeOrderChangeOrderId = Assert<Assignable<typeof page.cmdUpdateChangeOrderChangeOrderId, string | CmdUpdateChangeOrderInput["changeOrderId"]>>;
type _State_cmdUpdateChangeOrderClientRef = Assert<Assignable<typeof page.cmdUpdateChangeOrderClientRef, string | CmdUpdateChangeOrderInput["clientRef"]>>;
type _State_cmdUpdateChangeOrderProjectRef = Assert<Assignable<typeof page.cmdUpdateChangeOrderProjectRef, string | CmdUpdateChangeOrderInput["projectRef"]>>;
type _State_cmdUpdateChangeOrderDescription = Assert<Assignable<typeof page.cmdUpdateChangeOrderDescription, string | CmdUpdateChangeOrderInput["description"]>>;
type _State_cmdUpdateChangeOrderScopeImpact = Assert<Assignable<typeof page.cmdUpdateChangeOrderScopeImpact, string | CmdUpdateChangeOrderInput["scopeImpact"]>>;
type _State_cmdUpdateChangeOrderScheduleImpact = Assert<Assignable<typeof page.cmdUpdateChangeOrderScheduleImpact, string | CmdUpdateChangeOrderInput["scheduleImpact"]>>;
type _State_cmdUpdateChangeOrderChangeAmount = Assert<Assignable<typeof page.cmdUpdateChangeOrderChangeAmount, string | CmdUpdateChangeOrderInput["changeAmount"]>>;
type _State_cmdUpdateChangeOrderSubmittedAt = Assert<Assignable<typeof page.cmdUpdateChangeOrderSubmittedAt, string | CmdUpdateChangeOrderInput["submittedAt"]>>;
type _State_cmdUpdateChangeOrderForwardedForClientApprovalAt = Assert<Assignable<typeof page.cmdUpdateChangeOrderForwardedForClientApprovalAt, string | CmdUpdateChangeOrderInput["forwardedForClientApprovalAt"]>>;
type _State_cmdUpdateChangeOrderStatus = Assert<Assignable<typeof page.cmdUpdateChangeOrderStatus, string | CmdUpdateChangeOrderInput["status"]>>;
type _State_cmdUpdateChangeOrderOutput = Assert<Assignable<typeof page.cmdUpdateChangeOrderOutput, CmdUpdateChangeOrderOutput | null>>;
type _State_cmdUpdateChangeOrderError = Assert<Assignable<typeof page.cmdUpdateChangeOrderError, string>>;
type _State_cmdDeleteChangeOrderState = Assert<Assignable<typeof page.cmdDeleteChangeOrderState, "idle" | "loading" | "success" | "error">>;
type _State_cmdDeleteChangeOrderChangeOrderId = Assert<Assignable<typeof page.cmdDeleteChangeOrderChangeOrderId, string | CmdDeleteChangeOrderInput["changeOrderId"]>>;
type _State_cmdDeleteChangeOrderOutput = Assert<Assignable<typeof page.cmdDeleteChangeOrderOutput, CmdDeleteChangeOrderOutput | null>>;
type _State_cmdDeleteChangeOrderError = Assert<Assignable<typeof page.cmdDeleteChangeOrderError, string>>;
type _State_qryClientPickerState = Assert<Assignable<typeof page.qryClientPickerState, "idle" | "loading" | "success" | "error">>;
type _State_qryClientPickerData = Assert<Assignable<typeof page.qryClientPickerData, unknown[] | QryClientPickerOutput>>;
type _State_qryProjectPickerState = Assert<Assignable<typeof page.qryProjectPickerState, "idle" | "loading" | "success" | "error">>;
type _State_qryProjectPickerData = Assert<Assignable<typeof page.qryProjectPickerData, unknown[] | QryProjectPickerOutput>>;
type _Action_loadQryListChangeOrder = Assert<Assignable<typeof page.loadQryListChangeOrder, (...args: any[]) => unknown>>;
type _Handler_handleQryListChangeOrderClick = Assert<Assignable<typeof page.handleQryListChangeOrderClick, (...args: any[]) => unknown>>;
type _Action_cmdCreateChangeOrder = Assert<Assignable<typeof page.cmdCreateChangeOrder, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateChangeOrderClick = Assert<Assignable<typeof page.handleCmdCreateChangeOrderClick, (...args: any[]) => unknown>>;
type _Action_cmdUpdateChangeOrder = Assert<Assignable<typeof page.cmdUpdateChangeOrder, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderClick = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderClick, (...args: any[]) => unknown>>;
type _Action_cmdDeleteChangeOrder = Assert<Assignable<typeof page.cmdDeleteChangeOrder, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteChangeOrderClick = Assert<Assignable<typeof page.handleCmdDeleteChangeOrderClick, (...args: any[]) => unknown>>;
type _Action_loadQryClientPicker = Assert<Assignable<typeof page.loadQryClientPicker, (...args: any[]) => unknown>>;
type _Handler_handleQryClientPickerClick = Assert<Assignable<typeof page.handleQryClientPickerClick, (...args: any[]) => unknown>>;
type _Action_loadQryProjectPicker = Assert<Assignable<typeof page.loadQryProjectPicker, (...args: any[]) => unknown>>;
type _Handler_handleQryProjectPickerClick = Assert<Assignable<typeof page.handleQryProjectPickerClick, (...args: any[]) => unknown>>;
type _Action_setCmdCreateChangeOrderClientClientId = Assert<Assignable<typeof page.setCmdCreateChangeOrderClientClientId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateChangeOrderClientClientIdChange = Assert<Assignable<typeof page.handleCmdCreateChangeOrderClientClientIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateChangeOrderProjectProjectId = Assert<Assignable<typeof page.setCmdCreateChangeOrderProjectProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateChangeOrderProjectProjectIdChange = Assert<Assignable<typeof page.handleCmdCreateChangeOrderProjectProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateChangeOrderDescription = Assert<Assignable<typeof page.setCmdCreateChangeOrderDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateChangeOrderDescriptionChange = Assert<Assignable<typeof page.handleCmdCreateChangeOrderDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateChangeOrderScopeImpact = Assert<Assignable<typeof page.setCmdCreateChangeOrderScopeImpact, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateChangeOrderScopeImpactChange = Assert<Assignable<typeof page.handleCmdCreateChangeOrderScopeImpactChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateChangeOrderScheduleImpact = Assert<Assignable<typeof page.setCmdCreateChangeOrderScheduleImpact, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateChangeOrderScheduleImpactChange = Assert<Assignable<typeof page.handleCmdCreateChangeOrderScheduleImpactChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateChangeOrderChangeAmount = Assert<Assignable<typeof page.setCmdCreateChangeOrderChangeAmount, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateChangeOrderChangeAmountChange = Assert<Assignable<typeof page.handleCmdCreateChangeOrderChangeAmountChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderChangeOrderId = Assert<Assignable<typeof page.setCmdUpdateChangeOrderChangeOrderId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderChangeOrderIdChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderChangeOrderIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderClientRef = Assert<Assignable<typeof page.setCmdUpdateChangeOrderClientRef, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderClientRefChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderClientRefChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderProjectRef = Assert<Assignable<typeof page.setCmdUpdateChangeOrderProjectRef, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderProjectRefChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderProjectRefChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderDescription = Assert<Assignable<typeof page.setCmdUpdateChangeOrderDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderDescriptionChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderScopeImpact = Assert<Assignable<typeof page.setCmdUpdateChangeOrderScopeImpact, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderScopeImpactChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderScopeImpactChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderScheduleImpact = Assert<Assignable<typeof page.setCmdUpdateChangeOrderScheduleImpact, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderScheduleImpactChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderScheduleImpactChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderChangeAmount = Assert<Assignable<typeof page.setCmdUpdateChangeOrderChangeAmount, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderChangeAmountChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderChangeAmountChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderSubmittedAt = Assert<Assignable<typeof page.setCmdUpdateChangeOrderSubmittedAt, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderSubmittedAtChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderSubmittedAtChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderForwardedForClientApprovalAt = Assert<Assignable<typeof page.setCmdUpdateChangeOrderForwardedForClientApprovalAt, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderForwardedForClientApprovalAtChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderForwardedForClientApprovalAtChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateChangeOrderStatus = Assert<Assignable<typeof page.setCmdUpdateChangeOrderStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateChangeOrderStatusChange = Assert<Assignable<typeof page.handleCmdUpdateChangeOrderStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdDeleteChangeOrderChangeOrderId = Assert<Assignable<typeof page.setCmdDeleteChangeOrderChangeOrderId, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteChangeOrderChangeOrderIdChange = Assert<Assignable<typeof page.handleCmdDeleteChangeOrderChangeOrderIdChange, (...args: any[]) => unknown>>;

export {};