/// <mls fileReference="_102046_/l2/buildFlowFsm/web/shared/consultClientProjectUpdates.ts" enhancement="_102020_/l2/enhancementAura"/>

import { CollabLitElement } from '/_102029_/l2/collabLitElement.js';
import { property } from 'lit/decorators.js';
import { execBff, type BffClientOptions } from '/_102029_/l2/bffClient.js';
import { getState, setState, subscribe, unsubscribe } from '/_102029_/l2/collabState.js';
import type {
  QryLocateProjectInput,
  QryLocateProjectOutput,
  QryInspectStatusReportInput,
  QryInspectStatusReportOutput,
  QryInspectClientBillingSummaryInput,
  QryInspectClientBillingSummaryOutput,
} from '/_102046_/l2/buildFlowFsm/web/contracts/consultClientProjectUpdates.js';
import {
  qryLocateProjectRoute,
  qryInspectStatusReportRoute,
  qryInspectClientBillingSummaryRoute,
} from '/_102046_/l2/buildFlowFsm/web/contracts/consultClientProjectUpdates.js';

export type {
  QryLocateProjectInput,
  QryLocateProjectOutput,
  QryInspectStatusReportInput,
  QryInspectStatusReportOutput,
  QryInspectClientBillingSummaryInput,
  QryInspectClientBillingSummaryOutput,
} from '/_102046_/l2/buildFlowFsm/web/contracts/consultClientProjectUpdates.js';

/// **collab_i18n_start**
const message_pt = {
  'section.consultClientProjectUpdates.locateProject.title': 'Obra selecionada',
  'organism.consultClientProjectUpdates.qryLocateProject.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.name.label': 'Name',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.address.label': 'Address',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedEndDate.label': 'Planned End Date',
  'section.consultClientProjectUpdates.inspectStatusReport.title': 'Atualizações da obra',
  'organism.consultClientProjectUpdates.qryInspectStatusReport.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.title.label': 'Title',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.content.label': 'Content',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'section.consultClientProjectUpdates.inspectClientBillingSummary.title': 'Resumo de faturamento',
  'organism.consultClientProjectUpdates.qryInspectClientBillingSummary.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderReferences.label': 'Approved Change Order References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoiceReferences.label': 'Invoice References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderAmount.label': 'Approved Change Order Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.billableAmount.label': 'Billable Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoicedAmount.label': 'Invoiced Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientAvailableAmount.label': 'Client Available Amount',
  'section.consultClientProjectUpdates.projectContextSection.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectUpdatesSection.title': 'Atualizações da obra',
  'section.consultClientProjectUpdates.projectOverview.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectInsights.title': 'Visão da obra',
};
export type MessageType = typeof message_pt;
const message_pt_br: MessageType = {
  'section.consultClientProjectUpdates.locateProject.title': 'Obra selecionada',
  'organism.consultClientProjectUpdates.qryLocateProject.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.name.label': 'Name',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.address.label': 'Address',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedEndDate.label': 'Planned End Date',
  'section.consultClientProjectUpdates.inspectStatusReport.title': 'Atualizações da obra',
  'organism.consultClientProjectUpdates.qryInspectStatusReport.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.title.label': 'Title',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.content.label': 'Content',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'section.consultClientProjectUpdates.inspectClientBillingSummary.title': 'Resumo de faturamento',
  'organism.consultClientProjectUpdates.qryInspectClientBillingSummary.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderReferences.label': 'Approved Change Order References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoiceReferences.label': 'Invoice References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderAmount.label': 'Approved Change Order Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.billableAmount.label': 'Billable Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoicedAmount.label': 'Invoiced Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientAvailableAmount.label': 'Client Available Amount',
  'section.consultClientProjectUpdates.projectContextSection.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectUpdatesSection.title': 'Atualizações da obra',
  'section.consultClientProjectUpdates.projectOverview.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectInsights.title': 'Visão da obra',
};
const message_en: MessageType = {
  'section.consultClientProjectUpdates.locateProject.title': 'Obra selecionada',
  'organism.consultClientProjectUpdates.qryLocateProject.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.name.label': 'Name',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.address.label': 'Address',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedEndDate.label': 'Planned End Date',
  'section.consultClientProjectUpdates.inspectStatusReport.title': 'Atualizações da obra',
  'organism.consultClientProjectUpdates.qryInspectStatusReport.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.title.label': 'Title',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.content.label': 'Content',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'section.consultClientProjectUpdates.inspectClientBillingSummary.title': 'Resumo de faturamento',
  'organism.consultClientProjectUpdates.qryInspectClientBillingSummary.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderReferences.label': 'Approved Change Order References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoiceReferences.label': 'Invoice References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderAmount.label': 'Approved Change Order Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.billableAmount.label': 'Billable Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoicedAmount.label': 'Invoiced Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientAvailableAmount.label': 'Client Available Amount',
  'section.consultClientProjectUpdates.projectContextSection.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectUpdatesSection.title': 'Atualizações da obra',
  'section.consultClientProjectUpdates.projectOverview.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectInsights.title': 'Visão da obra',
};
const message_es: MessageType = {
  'section.consultClientProjectUpdates.locateProject.title': 'Obra selecionada',
  'organism.consultClientProjectUpdates.qryLocateProject.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.title': 'Selecionar a obra que exige atenção',
  'intent.consultClientProjectUpdates.qryLocateProject.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.name.label': 'Name',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.address.label': 'Address',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.consultClientProjectUpdates.qryLocateProject.list.column.plannedEndDate.label': 'Planned End Date',
  'section.consultClientProjectUpdates.inspectStatusReport.title': 'Atualizações da obra',
  'organism.consultClientProjectUpdates.qryInspectStatusReport.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.title': 'Consultar o relatório de status publicado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.status.label': 'Status',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.title.label': 'Title',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.content.label': 'Content',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.consultClientProjectUpdates.qryInspectStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'section.consultClientProjectUpdates.inspectClientBillingSummary.title': 'Resumo de faturamento',
  'organism.consultClientProjectUpdates.qryInspectClientBillingSummary.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.title': 'Consultar o resumo de faturamento',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.empty': 'Nenhum registro encontrado',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientId.label': 'Client Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.projectId.label': 'Project Id',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderReferences.label': 'Approved Change Order References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoiceReferences.label': 'Invoice References',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.approvedChangeOrderAmount.label': 'Approved Change Order Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.billableAmount.label': 'Billable Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.invoicedAmount.label': 'Invoiced Amount',
  'intent.consultClientProjectUpdates.qryInspectClientBillingSummary.list.column.clientAvailableAmount.label': 'Client Available Amount',
  'section.consultClientProjectUpdates.projectContextSection.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectUpdatesSection.title': 'Atualizações da obra',
  'section.consultClientProjectUpdates.projectOverview.title': 'Obra selecionada',
  'section.consultClientProjectUpdates.projectInsights.title': 'Visão da obra',
};
export const messages: { [key: string]: MessageType } = { 'pt': message_pt, 'pt-br': message_pt_br, 'en': message_en, 'es': message_es };
/// **collab_i18n_end**

const SUBSCRIBED_STATE_KEYS: string[] = [
  'ui.consultClientProjectUpdates.status',
  'ui.consultClientProjectUpdates.action.qryLocateProject.status',
  'ui.consultClientProjectUpdates.data.qryLocateProject',
  'ui.consultClientProjectUpdates.action.qryInspectStatusReport.status',
  'ui.consultClientProjectUpdates.input.qryInspectStatusReport.statusReportStatusReportId',
  'ui.consultClientProjectUpdates.data.qryInspectStatusReport',
  'ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status',
  'ui.consultClientProjectUpdates.input.qryInspectClientBillingSummary.clientBillingSummaryClientId',
  'ui.consultClientProjectUpdates.data.qryInspectClientBillingSummary',
];

export class BuildFlowFsmConsultClientProjectUpdatesBase extends CollabLitElement {
  /** state status — pageStatus */
  @property() status: string = '';
  /** state qryLocateProjectState — actionStatus, values: idle|loading|success|error */
  @property() qryLocateProjectState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state qryLocateProjectData — queryResult, outputShape: array */
  @property() qryLocateProjectData: QryLocateProjectOutput[] = [];
  /** state qryInspectStatusReportState — actionStatus, values: idle|loading|success|error */
  @property() qryInspectStatusReportState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state qryInspectStatusReportStatusReportStatusReportId — input */
  @property() qryInspectStatusReportStatusReportStatusReportId: string = '';
  /** state qryInspectStatusReportData — queryResult, outputShape: object */
  @property() qryInspectStatusReportData: QryInspectStatusReportOutput | null = null;
  /** state qryInspectClientBillingSummaryState — actionStatus, values: idle|loading|success|error */
  @property() qryInspectClientBillingSummaryState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state qryInspectClientBillingSummaryClientBillingSummaryClientId — input */
  @property() qryInspectClientBillingSummaryClientBillingSummaryClientId: string = '';
  /** state qryInspectClientBillingSummaryData — queryResult, outputShape: object */
  @property() qryInspectClientBillingSummaryData: QryInspectClientBillingSummaryOutput | null = null;

  connectedCallback(): void {
    super.connectedCallback();
    this.initStateValue('ui.consultClientProjectUpdates.status', '');
    this.initStateValue('ui.consultClientProjectUpdates.action.qryLocateProject.status', 'idle');
    this.initStateValue('ui.consultClientProjectUpdates.data.qryLocateProject', []);
    this.initStateValue('ui.consultClientProjectUpdates.action.qryInspectStatusReport.status', 'idle');
    this.initStateValue('ui.consultClientProjectUpdates.input.qryInspectStatusReport.statusReportStatusReportId', '');
    this.initStateValue('ui.consultClientProjectUpdates.data.qryInspectStatusReport', null);
    this.initStateValue('ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status', 'idle');
    this.initStateValue('ui.consultClientProjectUpdates.input.qryInspectClientBillingSummary.clientBillingSummaryClientId', '');
    this.initStateValue('ui.consultClientProjectUpdates.data.qryInspectClientBillingSummary', null);
    subscribe(SUBSCRIBED_STATE_KEYS, this);
    void this.loadQryLocateProject();
  }

  disconnectedCallback(): void {
    unsubscribe(SUBSCRIBED_STATE_KEYS, this);
    super.disconnectedCallback();
  }

  /** handleIcaStateChange — collabState notify contract; maps state keys onto class fields */
  handleIcaStateChange(key: string, value: unknown): void {
    switch (key) {
      case 'ui.consultClientProjectUpdates.status':
        this.status = (value as string) ?? '';
        break;
      case 'ui.consultClientProjectUpdates.action.qryLocateProject.status':
        this.qryLocateProjectState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.consultClientProjectUpdates.data.qryLocateProject':
        this.qryLocateProjectData = (value as QryLocateProjectOutput[]) ?? [];
        break;
      case 'ui.consultClientProjectUpdates.action.qryInspectStatusReport.status':
        this.qryInspectStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.consultClientProjectUpdates.input.qryInspectStatusReport.statusReportStatusReportId':
        this.qryInspectStatusReportStatusReportStatusReportId = (value as string) ?? '';
        break;
      case 'ui.consultClientProjectUpdates.data.qryInspectStatusReport':
        this.qryInspectStatusReportData = (value as QryInspectStatusReportOutput | null) ?? null;
        break;
      case 'ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status':
        this.qryInspectClientBillingSummaryState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.consultClientProjectUpdates.input.qryInspectClientBillingSummary.clientBillingSummaryClientId':
        this.qryInspectClientBillingSummaryClientBillingSummaryClientId = (value as string) ?? '';
        break;
      case 'ui.consultClientProjectUpdates.data.qryInspectClientBillingSummary':
        this.qryInspectClientBillingSummaryData = (value as QryInspectClientBillingSummaryOutput | null) ?? null;
        break;
      default:
        break;
    }
    this.requestUpdate();
  }

  private initStateValue(stateKey: string, defaultValue: unknown): void {
    const existing: unknown = getState(stateKey);
    const value: unknown = existing !== undefined ? existing : defaultValue;
    switch (stateKey) {
      case 'ui.consultClientProjectUpdates.status':
        this.status = (value as string) ?? '';
        break;
      case 'ui.consultClientProjectUpdates.action.qryLocateProject.status':
        this.qryLocateProjectState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.consultClientProjectUpdates.data.qryLocateProject':
        this.qryLocateProjectData = (value as QryLocateProjectOutput[]) ?? [];
        break;
      case 'ui.consultClientProjectUpdates.action.qryInspectStatusReport.status':
        this.qryInspectStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.consultClientProjectUpdates.input.qryInspectStatusReport.statusReportStatusReportId':
        this.qryInspectStatusReportStatusReportStatusReportId = (value as string) ?? '';
        break;
      case 'ui.consultClientProjectUpdates.data.qryInspectStatusReport':
        this.qryInspectStatusReportData = (value as QryInspectStatusReportOutput | null) ?? null;
        break;
      case 'ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status':
        this.qryInspectClientBillingSummaryState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.consultClientProjectUpdates.input.qryInspectClientBillingSummary.clientBillingSummaryClientId':
        this.qryInspectClientBillingSummaryClientBillingSummaryClientId = (value as string) ?? '';
        break;
      case 'ui.consultClientProjectUpdates.data.qryInspectClientBillingSummary':
        this.qryInspectClientBillingSummaryData = (value as QryInspectClientBillingSummaryOutput | null) ?? null;
        break;
      default:
        break;
    }
    if (existing === undefined) {
      setState(stateKey, value);
    }
  }

  /** action qryLocateProject (query) — route buildFlowFsm.consultClientProjectUpdates.qryLocateProject; inputs: (none); writes ui.consultClientProjectUpdates.data.qryLocateProject; status ui.consultClientProjectUpdates.action.qryLocateProject.status */
  async loadQryLocateProject(): Promise<void> {
    this.qryLocateProjectState = 'loading';
    setState('ui.consultClientProjectUpdates.action.qryLocateProject.status', 'loading');
    const params: QryLocateProjectInput = {
    };
    const options: BffClientOptions = { mode: 'silent' };
    const response = await execBff<QryLocateProjectOutput[]>(qryLocateProjectRoute, params, options);
    if (response.ok) {
      const data = response.data ?? [];
      this.qryLocateProjectData = data;
      setState('ui.consultClientProjectUpdates.data.qryLocateProject', data);
      this.qryLocateProjectState = 'success';
      setState('ui.consultClientProjectUpdates.action.qryLocateProject.status', 'success');
    } else {
      this.qryLocateProjectState = 'error';
      setState('ui.consultClientProjectUpdates.action.qryLocateProject.status', 'error');
      if (response.error) {
        console.error('qryLocateProject failed', response.error);
      }
    }
    this.requestUpdate();
  }

  /** handler for action qryLocateProject — bind UI events here */
  handleQryLocateProjectClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void this.loadQryLocateProject();
  }

  /** action qryInspectStatusReport (query) — route buildFlowFsm.consultClientProjectUpdates.qryInspectStatusReport; inputs: statusReportStatusReportId; writes ui.consultClientProjectUpdates.data.qryInspectStatusReport; status ui.consultClientProjectUpdates.action.qryInspectStatusReport.status */
  async loadQryInspectStatusReport(): Promise<void> {
    if (!this.qryInspectStatusReportStatusReportStatusReportId) {
      this.qryInspectStatusReportState = 'idle';
      setState('ui.consultClientProjectUpdates.action.qryInspectStatusReport.status', 'idle');
      this.requestUpdate();
      return;
    }
    this.qryInspectStatusReportState = 'loading';
    setState('ui.consultClientProjectUpdates.action.qryInspectStatusReport.status', 'loading');
    const params: QryInspectStatusReportInput = {
      statusReportStatusReportId: this.qryInspectStatusReportStatusReportStatusReportId,
    };
    const options: BffClientOptions = { mode: 'silent' };
    const response = await execBff<QryInspectStatusReportOutput>(qryInspectStatusReportRoute, params, options);
    if (response.ok) {
      const data = response.data ?? null;
      this.qryInspectStatusReportData = data;
      setState('ui.consultClientProjectUpdates.data.qryInspectStatusReport', data);
      this.qryInspectStatusReportState = 'success';
      setState('ui.consultClientProjectUpdates.action.qryInspectStatusReport.status', 'success');
    } else {
      this.qryInspectStatusReportState = 'error';
      setState('ui.consultClientProjectUpdates.action.qryInspectStatusReport.status', 'error');
      if (response.error) {
        console.error('qryInspectStatusReport failed', response.error);
      }
    }
    this.requestUpdate();
  }

  /** handler for action qryInspectStatusReport — bind UI events here */
  handleQryInspectStatusReportClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void this.loadQryInspectStatusReport();
  }

  /** action qryInspectClientBillingSummary (query) — route buildFlowFsm.consultClientProjectUpdates.qryInspectClientBillingSummary; inputs: clientBillingSummaryClientId; writes ui.consultClientProjectUpdates.data.qryInspectClientBillingSummary; status ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status */
  async loadQryInspectClientBillingSummary(): Promise<void> {
    if (!this.qryInspectClientBillingSummaryClientBillingSummaryClientId) {
      this.qryInspectClientBillingSummaryState = 'idle';
      setState('ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status', 'idle');
      this.requestUpdate();
      return;
    }
    this.qryInspectClientBillingSummaryState = 'loading';
    setState('ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status', 'loading');
    const params: QryInspectClientBillingSummaryInput = {
      clientBillingSummaryClientId: this.qryInspectClientBillingSummaryClientBillingSummaryClientId,
    };
    const options: BffClientOptions = { mode: 'silent' };
    const response = await execBff<QryInspectClientBillingSummaryOutput>(qryInspectClientBillingSummaryRoute, params, options);
    if (response.ok) {
      const data = response.data ?? null;
      this.qryInspectClientBillingSummaryData = data;
      setState('ui.consultClientProjectUpdates.data.qryInspectClientBillingSummary', data);
      this.qryInspectClientBillingSummaryState = 'success';
      setState('ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status', 'success');
    } else {
      this.qryInspectClientBillingSummaryState = 'error';
      setState('ui.consultClientProjectUpdates.action.qryInspectClientBillingSummary.status', 'error');
      if (response.error) {
        console.error('qryInspectClientBillingSummary failed', response.error);
      }
    }
    this.requestUpdate();
  }

  /** handler for action qryInspectClientBillingSummary — bind UI events here */
  handleQryInspectClientBillingSummaryClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void this.loadQryInspectClientBillingSummary();
  }

  /** setter for state ui.consultClientProjectUpdates.input.qryInspectStatusReport.statusReportStatusReportId */
  setQryInspectStatusReportStatusReportStatusReportId(value: string): void {
    this.qryInspectStatusReportStatusReportStatusReportId = value;
    setState('ui.consultClientProjectUpdates.input.qryInspectStatusReport.statusReportStatusReportId', value);
    this.requestUpdate();
  }

  /** handler for action set.qryInspectStatusReportStatusReportStatusReportId — bind UI events here */
  handleQryInspectStatusReportStatusReportStatusReportIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setQryInspectStatusReportStatusReportStatusReportId(value);
  }

  /** setter for state ui.consultClientProjectUpdates.input.qryInspectClientBillingSummary.clientBillingSummaryClientId */
  setQryInspectClientBillingSummaryClientBillingSummaryClientId(value: string): void {
    this.qryInspectClientBillingSummaryClientBillingSummaryClientId = value;
    setState('ui.consultClientProjectUpdates.input.qryInspectClientBillingSummary.clientBillingSummaryClientId', value);
    this.requestUpdate();
  }

  /** handler for action set.qryInspectClientBillingSummaryClientBillingSummaryClientId — bind UI events here */
  handleQryInspectClientBillingSummaryClientBillingSummaryClientIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setQryInspectClientBillingSummaryClientBillingSummaryClientId(value);
  }
}
