/// <mls fileReference="_102046_/l2/buildFlowFsm/web/shared/generateAndPublishProjectStatusReport.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmGenerateAndPublishProjectStatusReportBase } from '/_102046_/l2/buildFlowFsm/web/shared/generateAndPublishProjectStatusReport.js';
import type { CmdCreateStatusReportInput, CmdCreateStatusReportOutput, CmdHandoffStatusReportToClientInput, CmdHandoffStatusReportToClientOutput, CmdPublishStatusReportInput, CmdPublishStatusReportOutput, QryInspectProjectExecutionOverviewInput, QryInspectProjectExecutionOverviewOutput, QryInspectScheduleRiskAssessmentInput, QryInspectScheduleRiskAssessmentOutput, QryLocateProjectOutput } from '/_102046_/l2/buildFlowFsm/web/contracts/generateAndPublishProjectStatusReport.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmGenerateAndPublishProjectStatusReportBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_qryLocateProjectState = Assert<Assignable<typeof page.qryLocateProjectState, "idle" | "loading" | "success" | "error">>;
type _State_qryLocateProjectData = Assert<Assignable<typeof page.qryLocateProjectData, unknown[] | QryLocateProjectOutput>>;
type _State_qryInspectProjectExecutionOverviewState = Assert<Assignable<typeof page.qryInspectProjectExecutionOverviewState, "idle" | "loading" | "success" | "error">>;
type _State_qryInspectProjectExecutionOverviewProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.qryInspectProjectExecutionOverviewProjectExecutionOverviewProjectId, string | QryInspectProjectExecutionOverviewInput["projectExecutionOverviewProjectId"]>>;
type _State_qryInspectProjectExecutionOverviewData = Assert<Assignable<typeof page.qryInspectProjectExecutionOverviewData, QryInspectProjectExecutionOverviewOutput | null>>;
type _State_qryInspectScheduleRiskAssessmentState = Assert<Assignable<typeof page.qryInspectScheduleRiskAssessmentState, "idle" | "loading" | "success" | "error">>;
type _State_qryInspectScheduleRiskAssessmentScheduleRiskAssessmentProjectId = Assert<Assignable<typeof page.qryInspectScheduleRiskAssessmentScheduleRiskAssessmentProjectId, string | QryInspectScheduleRiskAssessmentInput["scheduleRiskAssessmentProjectId"]>>;
type _State_qryInspectScheduleRiskAssessmentData = Assert<Assignable<typeof page.qryInspectScheduleRiskAssessmentData, QryInspectScheduleRiskAssessmentOutput | null>>;
type _State_cmdCreateStatusReportState = Assert<Assignable<typeof page.cmdCreateStatusReportState, "idle" | "loading" | "success" | "error">>;
type _State_cmdCreateStatusReportProjectProjectId = Assert<Assignable<typeof page.cmdCreateStatusReportProjectProjectId, string | CmdCreateStatusReportInput["projectProjectId"]>>;
type _State_cmdCreateStatusReportProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.cmdCreateStatusReportProjectExecutionOverviewProjectId, string | CmdCreateStatusReportInput["projectExecutionOverviewProjectId"]>>;
type _State_cmdCreateStatusReportTitle = Assert<Assignable<typeof page.cmdCreateStatusReportTitle, string | CmdCreateStatusReportInput["title"]>>;
type _State_cmdCreateStatusReportContent = Assert<Assignable<typeof page.cmdCreateStatusReportContent, string | CmdCreateStatusReportInput["content"]>>;
type _State_cmdCreateStatusReportCommunicatedRisks = Assert<Assignable<typeof page.cmdCreateStatusReportCommunicatedRisks, string | CmdCreateStatusReportInput["communicatedRisks"]>>;
type _State_cmdCreateStatusReportGeneratedByUserId = Assert<Assignable<typeof page.cmdCreateStatusReportGeneratedByUserId, string | CmdCreateStatusReportInput["generatedByUserId"]>>;
type _State_cmdCreateStatusReportPublishedByUserId = Assert<Assignable<typeof page.cmdCreateStatusReportPublishedByUserId, string | CmdCreateStatusReportInput["publishedByUserId"]>>;
type _State_cmdCreateStatusReportOutput = Assert<Assignable<typeof page.cmdCreateStatusReportOutput, CmdCreateStatusReportOutput | null>>;
type _State_cmdCreateStatusReportError = Assert<Assignable<typeof page.cmdCreateStatusReportError, string>>;
type _State_cmdPublishStatusReportState = Assert<Assignable<typeof page.cmdPublishStatusReportState, "idle" | "loading" | "success" | "error">>;
type _State_cmdPublishStatusReportProjectProjectId = Assert<Assignable<typeof page.cmdPublishStatusReportProjectProjectId, string | CmdPublishStatusReportInput["projectProjectId"]>>;
type _State_cmdPublishStatusReportProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.cmdPublishStatusReportProjectExecutionOverviewProjectId, string | CmdPublishStatusReportInput["projectExecutionOverviewProjectId"]>>;
type _State_cmdPublishStatusReportStatusReportStatusReportId = Assert<Assignable<typeof page.cmdPublishStatusReportStatusReportStatusReportId, string | CmdPublishStatusReportInput["statusReportStatusReportId"]>>;
type _State_cmdPublishStatusReportStatus = Assert<Assignable<typeof page.cmdPublishStatusReportStatus, string | CmdPublishStatusReportInput["status"]>>;
type _State_cmdPublishStatusReportOutput = Assert<Assignable<typeof page.cmdPublishStatusReportOutput, CmdPublishStatusReportOutput | null>>;
type _State_cmdPublishStatusReportError = Assert<Assignable<typeof page.cmdPublishStatusReportError, string>>;
type _State_cmdHandoffStatusReportToClientState = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientState, "idle" | "loading" | "success" | "error">>;
type _State_cmdHandoffStatusReportToClientStatusReportStatusReportId = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientStatusReportStatusReportId, string | CmdHandoffStatusReportToClientInput["statusReportStatusReportId"]>>;
type _State_cmdHandoffStatusReportToClientTitle = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientTitle, string | CmdHandoffStatusReportToClientInput["title"]>>;
type _State_cmdHandoffStatusReportToClientContent = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientContent, string | CmdHandoffStatusReportToClientInput["content"]>>;
type _State_cmdHandoffStatusReportToClientCommunicatedRisks = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientCommunicatedRisks, string | CmdHandoffStatusReportToClientInput["communicatedRisks"]>>;
type _State_cmdHandoffStatusReportToClientGeneratedByUserId = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientGeneratedByUserId, string | CmdHandoffStatusReportToClientInput["generatedByUserId"]>>;
type _State_cmdHandoffStatusReportToClientPublishedByUserId = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientPublishedByUserId, string | CmdHandoffStatusReportToClientInput["publishedByUserId"]>>;
type _State_cmdHandoffStatusReportToClientOutput = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientOutput, CmdHandoffStatusReportToClientOutput | null>>;
type _State_cmdHandoffStatusReportToClientError = Assert<Assignable<typeof page.cmdHandoffStatusReportToClientError, string>>;
type _Action_loadQryLocateProject = Assert<Assignable<typeof page.loadQryLocateProject, (...args: any[]) => unknown>>;
type _Handler_handleQryLocateProjectClick = Assert<Assignable<typeof page.handleQryLocateProjectClick, (...args: any[]) => unknown>>;
type _Action_loadQryInspectProjectExecutionOverview = Assert<Assignable<typeof page.loadQryInspectProjectExecutionOverview, (...args: any[]) => unknown>>;
type _Handler_handleQryInspectProjectExecutionOverviewClick = Assert<Assignable<typeof page.handleQryInspectProjectExecutionOverviewClick, (...args: any[]) => unknown>>;
type _Action_loadQryInspectScheduleRiskAssessment = Assert<Assignable<typeof page.loadQryInspectScheduleRiskAssessment, (...args: any[]) => unknown>>;
type _Handler_handleQryInspectScheduleRiskAssessmentClick = Assert<Assignable<typeof page.handleQryInspectScheduleRiskAssessmentClick, (...args: any[]) => unknown>>;
type _Action_cmdCreateStatusReport = Assert<Assignable<typeof page.cmdCreateStatusReport, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportClick = Assert<Assignable<typeof page.handleCmdCreateStatusReportClick, (...args: any[]) => unknown>>;
type _Action_cmdPublishStatusReport = Assert<Assignable<typeof page.cmdPublishStatusReport, (...args: any[]) => unknown>>;
type _Handler_handleCmdPublishStatusReportClick = Assert<Assignable<typeof page.handleCmdPublishStatusReportClick, (...args: any[]) => unknown>>;
type _Action_cmdHandoffStatusReportToClient = Assert<Assignable<typeof page.cmdHandoffStatusReportToClient, (...args: any[]) => unknown>>;
type _Handler_handleCmdHandoffStatusReportToClientClick = Assert<Assignable<typeof page.handleCmdHandoffStatusReportToClientClick, (...args: any[]) => unknown>>;
type _Action_setQryInspectProjectExecutionOverviewProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.setQryInspectProjectExecutionOverviewProjectExecutionOverviewProjectId, (...args: any[]) => unknown>>;
type _Handler_handleQryInspectProjectExecutionOverviewProjectExecutionOverviewProjectIdChange = Assert<Assignable<typeof page.handleQryInspectProjectExecutionOverviewProjectExecutionOverviewProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setQryInspectScheduleRiskAssessmentScheduleRiskAssessmentProjectId = Assert<Assignable<typeof page.setQryInspectScheduleRiskAssessmentScheduleRiskAssessmentProjectId, (...args: any[]) => unknown>>;
type _Handler_handleQryInspectScheduleRiskAssessmentScheduleRiskAssessmentProjectIdChange = Assert<Assignable<typeof page.handleQryInspectScheduleRiskAssessmentScheduleRiskAssessmentProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportProjectProjectId = Assert<Assignable<typeof page.setCmdCreateStatusReportProjectProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportProjectProjectIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportProjectProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.setCmdCreateStatusReportProjectExecutionOverviewProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportProjectExecutionOverviewProjectIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportProjectExecutionOverviewProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportTitle = Assert<Assignable<typeof page.setCmdCreateStatusReportTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportTitleChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportContent = Assert<Assignable<typeof page.setCmdCreateStatusReportContent, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportContentChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportContentChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportCommunicatedRisks = Assert<Assignable<typeof page.setCmdCreateStatusReportCommunicatedRisks, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportCommunicatedRisksChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportCommunicatedRisksChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportGeneratedByUserId = Assert<Assignable<typeof page.setCmdCreateStatusReportGeneratedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportGeneratedByUserIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportGeneratedByUserIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportPublishedByUserId = Assert<Assignable<typeof page.setCmdCreateStatusReportPublishedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportPublishedByUserIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportPublishedByUserIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdPublishStatusReportProjectProjectId = Assert<Assignable<typeof page.setCmdPublishStatusReportProjectProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdPublishStatusReportProjectProjectIdChange = Assert<Assignable<typeof page.handleCmdPublishStatusReportProjectProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdPublishStatusReportProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.setCmdPublishStatusReportProjectExecutionOverviewProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdPublishStatusReportProjectExecutionOverviewProjectIdChange = Assert<Assignable<typeof page.handleCmdPublishStatusReportProjectExecutionOverviewProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdPublishStatusReportStatusReportStatusReportId = Assert<Assignable<typeof page.setCmdPublishStatusReportStatusReportStatusReportId, (...args: any[]) => unknown>>;
type _Handler_handleCmdPublishStatusReportStatusReportStatusReportIdChange = Assert<Assignable<typeof page.handleCmdPublishStatusReportStatusReportStatusReportIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdPublishStatusReportStatus = Assert<Assignable<typeof page.setCmdPublishStatusReportStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdPublishStatusReportStatusChange = Assert<Assignable<typeof page.handleCmdPublishStatusReportStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdHandoffStatusReportToClientStatusReportStatusReportId = Assert<Assignable<typeof page.setCmdHandoffStatusReportToClientStatusReportStatusReportId, (...args: any[]) => unknown>>;
type _Handler_handleCmdHandoffStatusReportToClientStatusReportStatusReportIdChange = Assert<Assignable<typeof page.handleCmdHandoffStatusReportToClientStatusReportStatusReportIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdHandoffStatusReportToClientTitle = Assert<Assignable<typeof page.setCmdHandoffStatusReportToClientTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdHandoffStatusReportToClientTitleChange = Assert<Assignable<typeof page.handleCmdHandoffStatusReportToClientTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdHandoffStatusReportToClientContent = Assert<Assignable<typeof page.setCmdHandoffStatusReportToClientContent, (...args: any[]) => unknown>>;
type _Handler_handleCmdHandoffStatusReportToClientContentChange = Assert<Assignable<typeof page.handleCmdHandoffStatusReportToClientContentChange, (...args: any[]) => unknown>>;
type _Action_setCmdHandoffStatusReportToClientCommunicatedRisks = Assert<Assignable<typeof page.setCmdHandoffStatusReportToClientCommunicatedRisks, (...args: any[]) => unknown>>;
type _Handler_handleCmdHandoffStatusReportToClientCommunicatedRisksChange = Assert<Assignable<typeof page.handleCmdHandoffStatusReportToClientCommunicatedRisksChange, (...args: any[]) => unknown>>;
type _Action_setCmdHandoffStatusReportToClientGeneratedByUserId = Assert<Assignable<typeof page.setCmdHandoffStatusReportToClientGeneratedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdHandoffStatusReportToClientGeneratedByUserIdChange = Assert<Assignable<typeof page.handleCmdHandoffStatusReportToClientGeneratedByUserIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdHandoffStatusReportToClientPublishedByUserId = Assert<Assignable<typeof page.setCmdHandoffStatusReportToClientPublishedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdHandoffStatusReportToClientPublishedByUserIdChange = Assert<Assignable<typeof page.handleCmdHandoffStatusReportToClientPublishedByUserIdChange, (...args: any[]) => unknown>>;

export {};