/// <mls fileReference="_102046_/l2/buildFlowFsm/web/shared/materialUsageCatalogue.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmMaterialUsageCatalogueBase } from '/_102046_/l2/buildFlowFsm/web/shared/materialUsageCatalogue.js';
import type { CmdCreateMaterialUsageInput, CmdCreateMaterialUsageOutput, CmdDeleteMaterialUsageInput, CmdDeleteMaterialUsageOutput, CmdUpdateMaterialUsageInput, CmdUpdateMaterialUsageOutput, QryInventoryBalancePickerOutput, QryInventoryItemPickerOutput, QryListMaterialUsageOutput, QryProjectPickerOutput } from '/_102046_/l2/buildFlowFsm/web/contracts/materialUsageCatalogue.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmMaterialUsageCatalogueBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_qryListMaterialUsageState = Assert<Assignable<typeof page.qryListMaterialUsageState, "idle" | "loading" | "success" | "error">>;
type _State_qryListMaterialUsageData = Assert<Assignable<typeof page.qryListMaterialUsageData, unknown[] | QryListMaterialUsageOutput>>;
type _State_cmdCreateMaterialUsageState = Assert<Assignable<typeof page.cmdCreateMaterialUsageState, "idle" | "loading" | "success" | "error">>;
type _State_cmdCreateMaterialUsageInventoryBalanceInventoryBalanceId = Assert<Assignable<typeof page.cmdCreateMaterialUsageInventoryBalanceInventoryBalanceId, string | CmdCreateMaterialUsageInput["inventoryBalanceInventoryBalanceId"]>>;
type _State_cmdCreateMaterialUsageInventoryItemInventoryItemId = Assert<Assignable<typeof page.cmdCreateMaterialUsageInventoryItemInventoryItemId, string | CmdCreateMaterialUsageInput["inventoryItemInventoryItemId"]>>;
type _State_cmdCreateMaterialUsageProjectProjectId = Assert<Assignable<typeof page.cmdCreateMaterialUsageProjectProjectId, string | CmdCreateMaterialUsageInput["projectProjectId"]>>;
type _State_cmdCreateMaterialUsageQuantity = Assert<Assignable<typeof page.cmdCreateMaterialUsageQuantity, string | CmdCreateMaterialUsageInput["quantity"]>>;
type _State_cmdCreateMaterialUsageUsageDescription = Assert<Assignable<typeof page.cmdCreateMaterialUsageUsageDescription, string | CmdCreateMaterialUsageInput["usageDescription"]>>;
type _State_cmdCreateMaterialUsageConsumedOn = Assert<Assignable<typeof page.cmdCreateMaterialUsageConsumedOn, string | CmdCreateMaterialUsageInput["consumedOn"]>>;
type _State_cmdCreateMaterialUsageUnitCostBasis = Assert<Assignable<typeof page.cmdCreateMaterialUsageUnitCostBasis, string | CmdCreateMaterialUsageInput["unitCostBasis"]>>;
type _State_cmdCreateMaterialUsageOutput = Assert<Assignable<typeof page.cmdCreateMaterialUsageOutput, CmdCreateMaterialUsageOutput | null>>;
type _State_cmdCreateMaterialUsageError = Assert<Assignable<typeof page.cmdCreateMaterialUsageError, string>>;
type _State_cmdUpdateMaterialUsageState = Assert<Assignable<typeof page.cmdUpdateMaterialUsageState, "idle" | "loading" | "success" | "error">>;
type _State_cmdUpdateMaterialUsageMaterialUsageId = Assert<Assignable<typeof page.cmdUpdateMaterialUsageMaterialUsageId, string | CmdUpdateMaterialUsageInput["materialUsageId"]>>;
type _State_cmdUpdateMaterialUsageStatus = Assert<Assignable<typeof page.cmdUpdateMaterialUsageStatus, string | CmdUpdateMaterialUsageInput["status"]>>;
type _State_cmdUpdateMaterialUsageProjectId = Assert<Assignable<typeof page.cmdUpdateMaterialUsageProjectId, string | CmdUpdateMaterialUsageInput["projectId"]>>;
type _State_cmdUpdateMaterialUsageInventoryItemId = Assert<Assignable<typeof page.cmdUpdateMaterialUsageInventoryItemId, string | CmdUpdateMaterialUsageInput["inventoryItemId"]>>;
type _State_cmdUpdateMaterialUsageInventoryBalanceId = Assert<Assignable<typeof page.cmdUpdateMaterialUsageInventoryBalanceId, string | CmdUpdateMaterialUsageInput["inventoryBalanceId"]>>;
type _State_cmdUpdateMaterialUsageQuantity = Assert<Assignable<typeof page.cmdUpdateMaterialUsageQuantity, string | CmdUpdateMaterialUsageInput["quantity"]>>;
type _State_cmdUpdateMaterialUsageUsageDescription = Assert<Assignable<typeof page.cmdUpdateMaterialUsageUsageDescription, string | CmdUpdateMaterialUsageInput["usageDescription"]>>;
type _State_cmdUpdateMaterialUsageConsumedOn = Assert<Assignable<typeof page.cmdUpdateMaterialUsageConsumedOn, string | CmdUpdateMaterialUsageInput["consumedOn"]>>;
type _State_cmdUpdateMaterialUsageUnitCostBasis = Assert<Assignable<typeof page.cmdUpdateMaterialUsageUnitCostBasis, string | CmdUpdateMaterialUsageInput["unitCostBasis"]>>;
type _State_cmdUpdateMaterialUsageOutput = Assert<Assignable<typeof page.cmdUpdateMaterialUsageOutput, CmdUpdateMaterialUsageOutput | null>>;
type _State_cmdUpdateMaterialUsageError = Assert<Assignable<typeof page.cmdUpdateMaterialUsageError, string>>;
type _State_cmdDeleteMaterialUsageState = Assert<Assignable<typeof page.cmdDeleteMaterialUsageState, "idle" | "loading" | "success" | "error">>;
type _State_cmdDeleteMaterialUsageMaterialUsageId = Assert<Assignable<typeof page.cmdDeleteMaterialUsageMaterialUsageId, string | CmdDeleteMaterialUsageInput["materialUsageId"]>>;
type _State_cmdDeleteMaterialUsageOutput = Assert<Assignable<typeof page.cmdDeleteMaterialUsageOutput, CmdDeleteMaterialUsageOutput | null>>;
type _State_cmdDeleteMaterialUsageError = Assert<Assignable<typeof page.cmdDeleteMaterialUsageError, string>>;
type _State_qryInventoryBalancePickerState = Assert<Assignable<typeof page.qryInventoryBalancePickerState, "idle" | "loading" | "success" | "error">>;
type _State_qryInventoryBalancePickerData = Assert<Assignable<typeof page.qryInventoryBalancePickerData, unknown[] | QryInventoryBalancePickerOutput>>;
type _State_qryInventoryItemPickerState = Assert<Assignable<typeof page.qryInventoryItemPickerState, "idle" | "loading" | "success" | "error">>;
type _State_qryInventoryItemPickerData = Assert<Assignable<typeof page.qryInventoryItemPickerData, unknown[] | QryInventoryItemPickerOutput>>;
type _State_qryProjectPickerState = Assert<Assignable<typeof page.qryProjectPickerState, "idle" | "loading" | "success" | "error">>;
type _State_qryProjectPickerData = Assert<Assignable<typeof page.qryProjectPickerData, unknown[] | QryProjectPickerOutput>>;
type _Action_loadQryListMaterialUsage = Assert<Assignable<typeof page.loadQryListMaterialUsage, (...args: any[]) => unknown>>;
type _Handler_handleQryListMaterialUsageClick = Assert<Assignable<typeof page.handleQryListMaterialUsageClick, (...args: any[]) => unknown>>;
type _Action_cmdCreateMaterialUsage = Assert<Assignable<typeof page.cmdCreateMaterialUsage, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageClick = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageClick, (...args: any[]) => unknown>>;
type _Action_cmdUpdateMaterialUsage = Assert<Assignable<typeof page.cmdUpdateMaterialUsage, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageClick = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageClick, (...args: any[]) => unknown>>;
type _Action_cmdDeleteMaterialUsage = Assert<Assignable<typeof page.cmdDeleteMaterialUsage, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteMaterialUsageClick = Assert<Assignable<typeof page.handleCmdDeleteMaterialUsageClick, (...args: any[]) => unknown>>;
type _Action_loadQryInventoryBalancePicker = Assert<Assignable<typeof page.loadQryInventoryBalancePicker, (...args: any[]) => unknown>>;
type _Handler_handleQryInventoryBalancePickerClick = Assert<Assignable<typeof page.handleQryInventoryBalancePickerClick, (...args: any[]) => unknown>>;
type _Action_loadQryInventoryItemPicker = Assert<Assignable<typeof page.loadQryInventoryItemPicker, (...args: any[]) => unknown>>;
type _Handler_handleQryInventoryItemPickerClick = Assert<Assignable<typeof page.handleQryInventoryItemPickerClick, (...args: any[]) => unknown>>;
type _Action_loadQryProjectPicker = Assert<Assignable<typeof page.loadQryProjectPicker, (...args: any[]) => unknown>>;
type _Handler_handleQryProjectPickerClick = Assert<Assignable<typeof page.handleQryProjectPickerClick, (...args: any[]) => unknown>>;
type _Action_setCmdCreateMaterialUsageInventoryBalanceInventoryBalanceId = Assert<Assignable<typeof page.setCmdCreateMaterialUsageInventoryBalanceInventoryBalanceId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageInventoryBalanceInventoryBalanceIdChange = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageInventoryBalanceInventoryBalanceIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateMaterialUsageInventoryItemInventoryItemId = Assert<Assignable<typeof page.setCmdCreateMaterialUsageInventoryItemInventoryItemId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageInventoryItemInventoryItemIdChange = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageInventoryItemInventoryItemIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateMaterialUsageProjectProjectId = Assert<Assignable<typeof page.setCmdCreateMaterialUsageProjectProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageProjectProjectIdChange = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageProjectProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateMaterialUsageQuantity = Assert<Assignable<typeof page.setCmdCreateMaterialUsageQuantity, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageQuantityChange = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageQuantityChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateMaterialUsageUsageDescription = Assert<Assignable<typeof page.setCmdCreateMaterialUsageUsageDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageUsageDescriptionChange = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageUsageDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateMaterialUsageConsumedOn = Assert<Assignable<typeof page.setCmdCreateMaterialUsageConsumedOn, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageConsumedOnChange = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageConsumedOnChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateMaterialUsageUnitCostBasis = Assert<Assignable<typeof page.setCmdCreateMaterialUsageUnitCostBasis, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateMaterialUsageUnitCostBasisChange = Assert<Assignable<typeof page.handleCmdCreateMaterialUsageUnitCostBasisChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageMaterialUsageId = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageMaterialUsageId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageMaterialUsageIdChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageMaterialUsageIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageStatus = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageStatusChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageProjectId = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageProjectIdChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageInventoryItemId = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageInventoryItemId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageInventoryItemIdChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageInventoryItemIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageInventoryBalanceId = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageInventoryBalanceId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageInventoryBalanceIdChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageInventoryBalanceIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageQuantity = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageQuantity, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageQuantityChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageQuantityChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageUsageDescription = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageUsageDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageUsageDescriptionChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageUsageDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageConsumedOn = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageConsumedOn, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageConsumedOnChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageConsumedOnChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateMaterialUsageUnitCostBasis = Assert<Assignable<typeof page.setCmdUpdateMaterialUsageUnitCostBasis, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateMaterialUsageUnitCostBasisChange = Assert<Assignable<typeof page.handleCmdUpdateMaterialUsageUnitCostBasisChange, (...args: any[]) => unknown>>;
type _Action_setCmdDeleteMaterialUsageMaterialUsageId = Assert<Assignable<typeof page.setCmdDeleteMaterialUsageMaterialUsageId, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteMaterialUsageMaterialUsageIdChange = Assert<Assignable<typeof page.handleCmdDeleteMaterialUsageMaterialUsageIdChange, (...args: any[]) => unknown>>;

export {};