/// <mls fileReference="_102046_/l2/buildFlowFsm/web/shared/statusReportCatalogue.ts" enhancement="_102020_/l2/enhancementAura"/>

import { CollabLitElement } from '/_102029_/l2/collabLitElement.js';
import { property } from 'lit/decorators.js';
import { execBff, type BffClientOptions } from '/_102029_/l2/bffClient.js';
import { getState, setState, subscribe, unsubscribe } from '/_102029_/l2/collabState.js';
import { runBlockingUiAction } from '/_102029_/l2/interactionRuntime.js';
import type {
  QryListStatusReportInput,
  QryListStatusReportOutput,
  CmdCreateStatusReportInput,
  CmdCreateStatusReportOutput,
  CmdUpdateStatusReportInput,
  CmdUpdateStatusReportOutput,
  CmdDeleteStatusReportInput,
  CmdDeleteStatusReportOutput,
  QryProjectPickerInput,
  QryProjectPickerOutput,
} from '/_102046_/l2/buildFlowFsm/web/contracts/statusReportCatalogue.js';
import {
  qryListStatusReportRoute,
  cmdCreateStatusReportRoute,
  cmdUpdateStatusReportRoute,
  cmdDeleteStatusReportRoute,
  qryProjectPickerRoute,
} from '/_102046_/l2/buildFlowFsm/web/contracts/statusReportCatalogue.js';

export type {
  QryListStatusReportInput,
  QryListStatusReportOutput,
  CmdCreateStatusReportInput,
  CmdCreateStatusReportOutput,
  CmdUpdateStatusReportInput,
  CmdUpdateStatusReportOutput,
  CmdDeleteStatusReportInput,
  CmdDeleteStatusReportOutput,
  QryProjectPickerInput,
  QryProjectPickerOutput,
} from '/_102046_/l2/buildFlowFsm/web/contracts/statusReportCatalogue.js';

/// **collab_i18n_start**
const message_pt = {
  'section.statusReportCatalogue.recordList.title': 'Relatórios disponíveis',
  'organism.statusReportCatalogue.qryListStatusReport.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.title.label': 'Title',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.content.label': 'Content',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'organism.statusReportCatalogue.cmdDeleteStatusReport.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.action.cmdDeleteStatusReport': 'Excluir Relatório de status',
  'section.statusReportCatalogue.recordForm.title': 'Gerar ou corrigir relatório',
  'organism.statusReportCatalogue.qryProjectPicker.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.clientId.label': 'Client Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.name.label': 'Name',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.address.label': 'Address',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedEndDate.label': 'Planned End Date',
  'organism.statusReportCatalogue.cmdCreateStatusReport.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.action.cmdCreateStatusReport': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'organism.statusReportCatalogue.cmdUpdateStatusReport.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.action.cmdUpdateStatusReport': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.status.label': 'Status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.withdrawnAt.label': 'Withdrawn At',
  'action.cmdCreateStatusReport.success': 'Gerar relatório profissional de status: OK',
  'action.cmdCreateStatusReport.error': 'Gerar relatório profissional de status: falhou',
  'action.cmdUpdateStatusReport.success': 'Atualizar Relatório de status: OK',
  'action.cmdUpdateStatusReport.error': 'Atualizar Relatório de status: falhou',
  'action.cmdDeleteStatusReport.success': 'Excluir Relatório de status: OK',
  'action.cmdDeleteStatusReport.error': 'Excluir Relatório de status: falhou',
};
export type MessageType = typeof message_pt;
const message_pt_br: MessageType = {
  'section.statusReportCatalogue.recordList.title': 'Relatórios disponíveis',
  'organism.statusReportCatalogue.qryListStatusReport.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.title.label': 'Title',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.content.label': 'Content',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'organism.statusReportCatalogue.cmdDeleteStatusReport.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.action.cmdDeleteStatusReport': 'Excluir Relatório de status',
  'section.statusReportCatalogue.recordForm.title': 'Gerar ou corrigir relatório',
  'organism.statusReportCatalogue.qryProjectPicker.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.clientId.label': 'Client Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.name.label': 'Name',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.address.label': 'Address',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedEndDate.label': 'Planned End Date',
  'organism.statusReportCatalogue.cmdCreateStatusReport.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.action.cmdCreateStatusReport': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'organism.statusReportCatalogue.cmdUpdateStatusReport.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.action.cmdUpdateStatusReport': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.status.label': 'Status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.withdrawnAt.label': 'Withdrawn At',
  'action.cmdCreateStatusReport.success': 'Gerar relatório profissional de status: OK',
  'action.cmdCreateStatusReport.error': 'Gerar relatório profissional de status: falhou',
  'action.cmdUpdateStatusReport.success': 'Atualizar Relatório de status: OK',
  'action.cmdUpdateStatusReport.error': 'Atualizar Relatório de status: falhou',
  'action.cmdDeleteStatusReport.success': 'Excluir Relatório de status: OK',
  'action.cmdDeleteStatusReport.error': 'Excluir Relatório de status: falhou',
};
const message_en: MessageType = {
  'section.statusReportCatalogue.recordList.title': 'Relatórios disponíveis',
  'organism.statusReportCatalogue.qryListStatusReport.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.title.label': 'Title',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.content.label': 'Content',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'organism.statusReportCatalogue.cmdDeleteStatusReport.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.action.cmdDeleteStatusReport': 'Excluir Relatório de status',
  'section.statusReportCatalogue.recordForm.title': 'Gerar ou corrigir relatório',
  'organism.statusReportCatalogue.qryProjectPicker.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.clientId.label': 'Client Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.name.label': 'Name',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.address.label': 'Address',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedEndDate.label': 'Planned End Date',
  'organism.statusReportCatalogue.cmdCreateStatusReport.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.action.cmdCreateStatusReport': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'organism.statusReportCatalogue.cmdUpdateStatusReport.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.action.cmdUpdateStatusReport': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.status.label': 'Status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.withdrawnAt.label': 'Withdrawn At',
  'action.cmdCreateStatusReport.success': 'Gerar relatório profissional de status: OK',
  'action.cmdCreateStatusReport.error': 'Gerar relatório profissional de status: falhou',
  'action.cmdUpdateStatusReport.success': 'Atualizar Relatório de status: OK',
  'action.cmdUpdateStatusReport.error': 'Atualizar Relatório de status: falhou',
  'action.cmdDeleteStatusReport.success': 'Excluir Relatório de status: OK',
  'action.cmdDeleteStatusReport.error': 'Excluir Relatório de status: falhou',
};
const message_es: MessageType = {
  'section.statusReportCatalogue.recordList.title': 'Relatórios disponíveis',
  'organism.statusReportCatalogue.qryListStatusReport.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.title': 'Listar Relatório de status',
  'intent.statusReportCatalogue.qryListStatusReport.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.statusReportId.label': 'Status Report Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.title.label': 'Title',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.content.label': 'Content',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.qryListStatusReport.list.column.withdrawnAt.label': 'Withdrawn At',
  'organism.statusReportCatalogue.cmdDeleteStatusReport.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.title': 'Excluir Relatório de status',
  'intent.statusReportCatalogue.cmdDeleteStatusReport.form.action.cmdDeleteStatusReport': 'Excluir Relatório de status',
  'section.statusReportCatalogue.recordForm.title': 'Gerar ou corrigir relatório',
  'organism.statusReportCatalogue.qryProjectPicker.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.title': 'Listar Obra',
  'intent.statusReportCatalogue.qryProjectPicker.list.empty': 'Nenhum registro encontrado',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.projectId.label': 'Project Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.clientId.label': 'Client Id',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.name.label': 'Name',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.address.label': 'Address',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.status.label': 'Status',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.authorizedBudget.label': 'Authorized Budget',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedStartDate.label': 'Planned Start Date',
  'intent.statusReportCatalogue.qryProjectPicker.list.column.plannedEndDate.label': 'Planned End Date',
  'organism.statusReportCatalogue.cmdCreateStatusReport.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.title': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.action.cmdCreateStatusReport': 'Gerar relatório profissional de status',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdCreateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'organism.statusReportCatalogue.cmdUpdateStatusReport.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.title': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.action.cmdUpdateStatusReport': 'Atualizar Relatório de status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.status.label': 'Status',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.title.label': 'Title',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.content.label': 'Content',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.communicatedRisks.label': 'Communicated Risks',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedAt.label': 'Generated At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.generatedByUserId.label': 'Generated By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedAt.label': 'Published At',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.publishedByUserId.label': 'Published By User Id',
  'intent.statusReportCatalogue.cmdUpdateStatusReport.form.field.withdrawnAt.label': 'Withdrawn At',
  'action.cmdCreateStatusReport.success': 'Gerar relatório profissional de status: OK',
  'action.cmdCreateStatusReport.error': 'Gerar relatório profissional de status: falhou',
  'action.cmdUpdateStatusReport.success': 'Atualizar Relatório de status: OK',
  'action.cmdUpdateStatusReport.error': 'Atualizar Relatório de status: falhou',
  'action.cmdDeleteStatusReport.success': 'Excluir Relatório de status: OK',
  'action.cmdDeleteStatusReport.error': 'Excluir Relatório de status: falhou',
};
export const messages: { [key: string]: MessageType } = { 'pt': message_pt, 'pt-br': message_pt_br, 'en': message_en, 'es': message_es };
/// **collab_i18n_end**

const SUBSCRIBED_STATE_KEYS: string[] = [
  'ui.statusReportCatalogue.status',
  'ui.statusReportCatalogue.action.qryListStatusReport.status',
  'ui.statusReportCatalogue.data.qryListStatusReport',
  'ui.statusReportCatalogue.action.cmdCreateStatusReport.status',
  'ui.statusReportCatalogue.input.cmdCreateStatusReport.projectProjectId',
  'ui.statusReportCatalogue.input.cmdCreateStatusReport.projectExecutionOverviewProjectId',
  'ui.statusReportCatalogue.input.cmdCreateStatusReport.title',
  'ui.statusReportCatalogue.input.cmdCreateStatusReport.content',
  'ui.statusReportCatalogue.input.cmdCreateStatusReport.communicatedRisks',
  'ui.statusReportCatalogue.input.cmdCreateStatusReport.generatedByUserId',
  'ui.statusReportCatalogue.input.cmdCreateStatusReport.publishedByUserId',
  'ui.statusReportCatalogue.output.cmdCreateStatusReport',
  'ui.statusReportCatalogue.action.cmdCreateStatusReport.error',
  'ui.statusReportCatalogue.action.cmdUpdateStatusReport.status',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.statusReportId',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.projectId',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.status',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.title',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.content',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId',
  'ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt',
  'ui.statusReportCatalogue.output.cmdUpdateStatusReport',
  'ui.statusReportCatalogue.action.cmdUpdateStatusReport.error',
  'ui.statusReportCatalogue.action.cmdDeleteStatusReport.status',
  'ui.statusReportCatalogue.input.cmdDeleteStatusReport.statusReportId',
  'ui.statusReportCatalogue.output.cmdDeleteStatusReport',
  'ui.statusReportCatalogue.action.cmdDeleteStatusReport.error',
  'ui.statusReportCatalogue.action.qryProjectPicker.status',
  'ui.statusReportCatalogue.data.qryProjectPicker',
];

export class BuildFlowFsmStatusReportCatalogueBase extends CollabLitElement {
  /** state status — pageStatus */
  @property() status: string = '';
  /** state qryListStatusReportState — actionStatus, values: idle|loading|success|error */
  @property() qryListStatusReportState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state qryListStatusReportData — queryResult, outputShape: array */
  @property() qryListStatusReportData: QryListStatusReportOutput[] = [];
  /** state cmdCreateStatusReportState — actionStatus, values: idle|loading|success|error */
  @property() cmdCreateStatusReportState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state cmdCreateStatusReportProjectProjectId — input */
  @property() cmdCreateStatusReportProjectProjectId: string = '';
  /** state cmdCreateStatusReportProjectExecutionOverviewProjectId — input */
  @property() cmdCreateStatusReportProjectExecutionOverviewProjectId: string = '';
  /** state cmdCreateStatusReportTitle — input */
  @property() cmdCreateStatusReportTitle: string = '';
  /** state cmdCreateStatusReportContent — input */
  @property() cmdCreateStatusReportContent: string = '';
  /** state cmdCreateStatusReportCommunicatedRisks — input */
  @property() cmdCreateStatusReportCommunicatedRisks: string = '';
  /** state cmdCreateStatusReportGeneratedByUserId — input */
  @property() cmdCreateStatusReportGeneratedByUserId: string = '';
  /** state cmdCreateStatusReportPublishedByUserId — input */
  @property() cmdCreateStatusReportPublishedByUserId: string = '';
  /** state cmdCreateStatusReportOutput — commandOutput */
  @property() cmdCreateStatusReportOutput: CmdCreateStatusReportOutput | null = null;
  /** state cmdCreateStatusReportError — actionError */
  @property() cmdCreateStatusReportError: string = '';
  /** state cmdUpdateStatusReportState — actionStatus, values: idle|loading|success|error */
  @property() cmdUpdateStatusReportState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state cmdUpdateStatusReportStatusReportId — input */
  @property() cmdUpdateStatusReportStatusReportId: string = '';
  /** state cmdUpdateStatusReportProjectId — input */
  @property() cmdUpdateStatusReportProjectId: string = '';
  /** state cmdUpdateStatusReportStatus — input */
  @property() cmdUpdateStatusReportStatus: string = '';
  /** state cmdUpdateStatusReportTitle — input */
  @property() cmdUpdateStatusReportTitle: string = '';
  /** state cmdUpdateStatusReportContent — input */
  @property() cmdUpdateStatusReportContent: string = '';
  /** state cmdUpdateStatusReportCommunicatedRisks — input */
  @property() cmdUpdateStatusReportCommunicatedRisks: string = '';
  /** state cmdUpdateStatusReportGeneratedAt — input */
  @property() cmdUpdateStatusReportGeneratedAt: string = '';
  /** state cmdUpdateStatusReportGeneratedByUserId — input */
  @property() cmdUpdateStatusReportGeneratedByUserId: string = '';
  /** state cmdUpdateStatusReportPublishedAt — input */
  @property() cmdUpdateStatusReportPublishedAt: string = '';
  /** state cmdUpdateStatusReportPublishedByUserId — input */
  @property() cmdUpdateStatusReportPublishedByUserId: string = '';
  /** state cmdUpdateStatusReportWithdrawnAt — input */
  @property() cmdUpdateStatusReportWithdrawnAt: string = '';
  /** state cmdUpdateStatusReportOutput — commandOutput */
  @property() cmdUpdateStatusReportOutput: CmdUpdateStatusReportOutput | null = null;
  /** state cmdUpdateStatusReportError — actionError */
  @property() cmdUpdateStatusReportError: string = '';
  /** state cmdDeleteStatusReportState — actionStatus, values: idle|loading|success|error */
  @property() cmdDeleteStatusReportState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state cmdDeleteStatusReportStatusReportId — input */
  @property() cmdDeleteStatusReportStatusReportId: string = '';
  /** state cmdDeleteStatusReportOutput — commandOutput */
  @property() cmdDeleteStatusReportOutput: CmdDeleteStatusReportOutput | null = null;
  /** state cmdDeleteStatusReportError — actionError */
  @property() cmdDeleteStatusReportError: string = '';
  /** state qryProjectPickerState — actionStatus, values: idle|loading|success|error */
  @property() qryProjectPickerState: 'idle' | 'loading' | 'success' | 'error' = 'idle';
  /** state qryProjectPickerData — queryResult, outputShape: array */
  @property() qryProjectPickerData: QryProjectPickerOutput[] = [];

  connectedCallback(): void {
    super.connectedCallback();
    this.initStateValue('ui.statusReportCatalogue.status', '');
    this.initStateValue('ui.statusReportCatalogue.action.qryListStatusReport.status', 'idle');
    this.initStateValue('ui.statusReportCatalogue.data.qryListStatusReport', []);
    this.initStateValue('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'idle');
    this.initStateValue('ui.statusReportCatalogue.input.cmdCreateStatusReport.projectProjectId', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdCreateStatusReport.projectExecutionOverviewProjectId', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdCreateStatusReport.title', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdCreateStatusReport.content', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdCreateStatusReport.communicatedRisks', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdCreateStatusReport.generatedByUserId', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdCreateStatusReport.publishedByUserId', '');
    this.initStateValue('ui.statusReportCatalogue.output.cmdCreateStatusReport', null);
    this.initStateValue('ui.statusReportCatalogue.action.cmdCreateStatusReport.error', '');
    this.initStateValue('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'idle');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.statusReportId', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.projectId', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.status', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.title', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.content', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId', '');
    this.initStateValue('ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt', '');
    this.initStateValue('ui.statusReportCatalogue.output.cmdUpdateStatusReport', null);
    this.initStateValue('ui.statusReportCatalogue.action.cmdUpdateStatusReport.error', '');
    this.initStateValue('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'idle');
    this.initStateValue('ui.statusReportCatalogue.input.cmdDeleteStatusReport.statusReportId', '');
    this.initStateValue('ui.statusReportCatalogue.output.cmdDeleteStatusReport', null);
    this.initStateValue('ui.statusReportCatalogue.action.cmdDeleteStatusReport.error', '');
    this.initStateValue('ui.statusReportCatalogue.action.qryProjectPicker.status', 'idle');
    this.initStateValue('ui.statusReportCatalogue.data.qryProjectPicker', []);
    this.syncRouteParams();
    subscribe(SUBSCRIBED_STATE_KEYS, this);
    void this.loadQryListStatusReport();
    void this.loadQryProjectPicker();
  }

  disconnectedCallback(): void {
    unsubscribe(SUBSCRIBED_STATE_KEYS, this);
    super.disconnectedCallback();
  }

  /** handleIcaStateChange — collabState notify contract; maps state keys onto class fields */
  handleIcaStateChange(key: string, value: unknown): void {
    switch (key) {
      case 'ui.statusReportCatalogue.status':
        this.status = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.qryListStatusReport.status':
        this.qryListStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.data.qryListStatusReport':
        this.qryListStatusReportData = (value as QryListStatusReportOutput[]) ?? [];
        break;
      case 'ui.statusReportCatalogue.action.cmdCreateStatusReport.status':
        this.cmdCreateStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.projectProjectId':
        this.cmdCreateStatusReportProjectProjectId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.projectExecutionOverviewProjectId':
        this.cmdCreateStatusReportProjectExecutionOverviewProjectId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.title':
        this.cmdCreateStatusReportTitle = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.content':
        this.cmdCreateStatusReportContent = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.communicatedRisks':
        this.cmdCreateStatusReportCommunicatedRisks = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.generatedByUserId':
        this.cmdCreateStatusReportGeneratedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.publishedByUserId':
        this.cmdCreateStatusReportPublishedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.output.cmdCreateStatusReport':
        this.cmdCreateStatusReportOutput = (value as CmdCreateStatusReportOutput | null) ?? null;
        break;
      case 'ui.statusReportCatalogue.action.cmdCreateStatusReport.error':
        this.cmdCreateStatusReportError = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.cmdUpdateStatusReport.status':
        this.cmdUpdateStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.statusReportId':
        this.cmdUpdateStatusReportStatusReportId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.projectId':
        this.cmdUpdateStatusReportProjectId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.status':
        this.cmdUpdateStatusReportStatus = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.title':
        this.cmdUpdateStatusReportTitle = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.content':
        this.cmdUpdateStatusReportContent = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks':
        this.cmdUpdateStatusReportCommunicatedRisks = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt':
        this.cmdUpdateStatusReportGeneratedAt = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId':
        this.cmdUpdateStatusReportGeneratedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt':
        this.cmdUpdateStatusReportPublishedAt = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId':
        this.cmdUpdateStatusReportPublishedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt':
        this.cmdUpdateStatusReportWithdrawnAt = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.output.cmdUpdateStatusReport':
        this.cmdUpdateStatusReportOutput = (value as CmdUpdateStatusReportOutput | null) ?? null;
        break;
      case 'ui.statusReportCatalogue.action.cmdUpdateStatusReport.error':
        this.cmdUpdateStatusReportError = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.cmdDeleteStatusReport.status':
        this.cmdDeleteStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.input.cmdDeleteStatusReport.statusReportId':
        this.cmdDeleteStatusReportStatusReportId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.output.cmdDeleteStatusReport':
        this.cmdDeleteStatusReportOutput = (value as CmdDeleteStatusReportOutput | null) ?? null;
        break;
      case 'ui.statusReportCatalogue.action.cmdDeleteStatusReport.error':
        this.cmdDeleteStatusReportError = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.qryProjectPicker.status':
        this.qryProjectPickerState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.data.qryProjectPicker':
        this.qryProjectPickerData = (value as QryProjectPickerOutput[]) ?? [];
        break;
      default:
        break;
    }
    this.requestUpdate();
  }

  private initStateValue(stateKey: string, defaultValue: unknown): void {
    const existing: unknown = getState(stateKey);
    const value: unknown = existing !== undefined ? existing : defaultValue;
    switch (stateKey) {
      case 'ui.statusReportCatalogue.status':
        this.status = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.qryListStatusReport.status':
        this.qryListStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.data.qryListStatusReport':
        this.qryListStatusReportData = (value as QryListStatusReportOutput[]) ?? [];
        break;
      case 'ui.statusReportCatalogue.action.cmdCreateStatusReport.status':
        this.cmdCreateStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.projectProjectId':
        this.cmdCreateStatusReportProjectProjectId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.projectExecutionOverviewProjectId':
        this.cmdCreateStatusReportProjectExecutionOverviewProjectId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.title':
        this.cmdCreateStatusReportTitle = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.content':
        this.cmdCreateStatusReportContent = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.communicatedRisks':
        this.cmdCreateStatusReportCommunicatedRisks = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.generatedByUserId':
        this.cmdCreateStatusReportGeneratedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdCreateStatusReport.publishedByUserId':
        this.cmdCreateStatusReportPublishedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.output.cmdCreateStatusReport':
        this.cmdCreateStatusReportOutput = (value as CmdCreateStatusReportOutput | null) ?? null;
        break;
      case 'ui.statusReportCatalogue.action.cmdCreateStatusReport.error':
        this.cmdCreateStatusReportError = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.cmdUpdateStatusReport.status':
        this.cmdUpdateStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.statusReportId':
        this.cmdUpdateStatusReportStatusReportId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.projectId':
        this.cmdUpdateStatusReportProjectId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.status':
        this.cmdUpdateStatusReportStatus = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.title':
        this.cmdUpdateStatusReportTitle = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.content':
        this.cmdUpdateStatusReportContent = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks':
        this.cmdUpdateStatusReportCommunicatedRisks = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt':
        this.cmdUpdateStatusReportGeneratedAt = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId':
        this.cmdUpdateStatusReportGeneratedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt':
        this.cmdUpdateStatusReportPublishedAt = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId':
        this.cmdUpdateStatusReportPublishedByUserId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt':
        this.cmdUpdateStatusReportWithdrawnAt = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.output.cmdUpdateStatusReport':
        this.cmdUpdateStatusReportOutput = (value as CmdUpdateStatusReportOutput | null) ?? null;
        break;
      case 'ui.statusReportCatalogue.action.cmdUpdateStatusReport.error':
        this.cmdUpdateStatusReportError = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.cmdDeleteStatusReport.status':
        this.cmdDeleteStatusReportState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.input.cmdDeleteStatusReport.statusReportId':
        this.cmdDeleteStatusReportStatusReportId = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.output.cmdDeleteStatusReport':
        this.cmdDeleteStatusReportOutput = (value as CmdDeleteStatusReportOutput | null) ?? null;
        break;
      case 'ui.statusReportCatalogue.action.cmdDeleteStatusReport.error':
        this.cmdDeleteStatusReportError = (value as string) ?? '';
        break;
      case 'ui.statusReportCatalogue.action.qryProjectPicker.status':
        this.qryProjectPickerState = (value as 'idle' | 'loading' | 'success' | 'error') ?? 'idle';
        break;
      case 'ui.statusReportCatalogue.data.qryProjectPicker':
        this.qryProjectPickerData = (value as QryProjectPickerOutput[]) ?? [];
        break;
      default:
        break;
    }
    if (existing === undefined) {
      setState(stateKey, value);
    }
  }

  private syncRouteParams(): void {
    const pathname: string = window.location.pathname;
    const match: RegExpMatchArray | null = pathname.match(
      /^\/buildFlowFsm\/statusReportCatalogue(?:\/([^/]+))?\/?$/,
    );
    const rawProjectProjectId: string = match && match[1] ? match[1] : '';
    let projectProjectId: string = '';
    if (rawProjectProjectId) {
      try {
        projectProjectId = decodeURIComponent(rawProjectProjectId);
      } catch {
        projectProjectId = rawProjectProjectId;
      }
    }
    if (projectProjectId) {
      if (!this.cmdCreateStatusReportProjectProjectId) {
        this.cmdCreateStatusReportProjectProjectId = projectProjectId;
        setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.projectProjectId', projectProjectId);
      }
    }
  }

  private readErrorMessage(error: unknown, fallback: string): string {
    if (error && typeof error === 'object') {
      const record = error as { message?: unknown; error?: unknown };
      if (typeof record.message === 'string' && record.message) {
        return record.message;
      }
      if (typeof record.error === 'string' && record.error) {
        return record.error;
      }
    }
    return fallback;
  }

  /** action qryListStatusReport (query) — route buildFlowFsm.statusReportCatalogue.qryListStatusReport; inputs: (none); writes ui.statusReportCatalogue.data.qryListStatusReport; status ui.statusReportCatalogue.action.qryListStatusReport.status */
  async loadQryListStatusReport(): Promise<void> {
    this.syncRouteParams();
    this.qryListStatusReportState = 'loading';
    setState('ui.statusReportCatalogue.action.qryListStatusReport.status', 'loading');
    const params: QryListStatusReportInput = {
    };
    const options: BffClientOptions = { mode: 'silent' };
    const response = await execBff<QryListStatusReportOutput[]>(qryListStatusReportRoute, params, options);
    if (response.ok) {
      const data = response.data ?? [];
      this.qryListStatusReportData = data;
      setState('ui.statusReportCatalogue.data.qryListStatusReport', data);
      this.qryListStatusReportState = 'success';
      setState('ui.statusReportCatalogue.action.qryListStatusReport.status', 'success');
    } else {
      this.qryListStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.qryListStatusReport.status', 'error');
      if (response.error) {
        console.error('qryListStatusReport failed', response.error);
      }
    }
    this.requestUpdate();
  }

  /** handler for action qryListStatusReport — bind UI events here */
  handleQryListStatusReportClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void this.loadQryListStatusReport();
  }

  /** action cmdCreateStatusReport (command) — route buildFlowFsm.statusReportCatalogue.cmdCreateStatusReport; inputs: projectProjectId, projectExecutionOverviewProjectId, title, content, communicatedRisks, generatedByUserId, publishedByUserId; writes ui.statusReportCatalogue.output.cmdCreateStatusReport; status ui.statusReportCatalogue.action.cmdCreateStatusReport.status; feedback keys action.cmdCreateStatusReport.success / action.cmdCreateStatusReport.error */
  async cmdCreateStatusReport(): Promise<void> {
    this.syncRouteParams();
    if (!this.cmdCreateStatusReportProjectProjectId) {
      this.cmdCreateStatusReportState = 'idle';
      setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'idle');
      this.requestUpdate();
      return;
    }
    if (!this.cmdCreateStatusReportProjectExecutionOverviewProjectId) {
      this.cmdCreateStatusReportState = 'idle';
      setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'idle');
      this.requestUpdate();
      return;
    }
    this.cmdCreateStatusReportState = 'loading';
    setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'loading');
    this.cmdCreateStatusReportError = '';
    setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.error', '');
    const params: CmdCreateStatusReportInput = {
      projectProjectId: this.cmdCreateStatusReportProjectProjectId,
      projectExecutionOverviewProjectId: this.cmdCreateStatusReportProjectExecutionOverviewProjectId,
      title: this.cmdCreateStatusReportTitle,
      content: this.cmdCreateStatusReportContent,
      generatedByUserId: this.cmdCreateStatusReportGeneratedByUserId,
    };
    if (this.cmdCreateStatusReportCommunicatedRisks) {
      params.communicatedRisks = this.cmdCreateStatusReportCommunicatedRisks;
    }
    if (this.cmdCreateStatusReportPublishedByUserId) {
      params.publishedByUserId = this.cmdCreateStatusReportPublishedByUserId;
    }
    const options: BffClientOptions = { mode: 'blocking' };
    const response = await execBff<CmdCreateStatusReportOutput>(cmdCreateStatusReportRoute, params, options);
    if (!response.ok) {
      const errMsg: string = this.readErrorMessage(response.error, 'action.cmdCreateStatusReport.error');
      this.cmdCreateStatusReportError = errMsg;
      setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.error', errMsg);
      this.cmdCreateStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    const data: CmdCreateStatusReportOutput | null = response.data ?? null;
    this.cmdCreateStatusReportOutput = data;
    setState('ui.statusReportCatalogue.output.cmdCreateStatusReport', data);
    try {
      await this.loadQryListStatusReport();
      if (this.qryListStatusReportState === 'error') {
        this.cmdCreateStatusReportState = 'error';
        setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'error');
        this.requestUpdate();
        return;
      }
    } catch (refreshError: unknown) {
      console.error('cmdCreateStatusReport refresh failed', refreshError);
      this.cmdCreateStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    try {
      await this.loadQryProjectPicker();
      if (this.qryProjectPickerState === 'error') {
        this.cmdCreateStatusReportState = 'error';
        setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'error');
        this.requestUpdate();
        return;
      }
    } catch (refreshError: unknown) {
      console.error('cmdCreateStatusReport refresh failed', refreshError);
      this.cmdCreateStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    this.cmdCreateStatusReportProjectExecutionOverviewProjectId = '';
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.projectExecutionOverviewProjectId', '');
    this.cmdCreateStatusReportTitle = '';
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.title', '');
    this.cmdCreateStatusReportContent = '';
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.content', '');
    this.cmdCreateStatusReportCommunicatedRisks = '';
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.communicatedRisks', '');
    this.cmdCreateStatusReportGeneratedByUserId = '';
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.generatedByUserId', '');
    this.cmdCreateStatusReportPublishedByUserId = '';
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.publishedByUserId', '');
    this.cmdCreateStatusReportState = 'success';
    setState('ui.statusReportCatalogue.action.cmdCreateStatusReport.status', 'success');
    this.requestUpdate();
  }

  /** handler for action cmdCreateStatusReport — bind UI events here */
  handleCmdCreateStatusReportClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void runBlockingUiAction(async (_signal: AbortSignal) => {
      await this.cmdCreateStatusReport();
    });
  }

  /** action cmdUpdateStatusReport (command) — route buildFlowFsm.statusReportCatalogue.cmdUpdateStatusReport; inputs: statusReportId, projectId, status, title, content, communicatedRisks, generatedAt, generatedByUserId, publishedAt, publishedByUserId, withdrawnAt; writes ui.statusReportCatalogue.output.cmdUpdateStatusReport; status ui.statusReportCatalogue.action.cmdUpdateStatusReport.status; feedback keys action.cmdUpdateStatusReport.success / action.cmdUpdateStatusReport.error */
  async cmdUpdateStatusReport(): Promise<void> {
    this.syncRouteParams();
    if (!this.cmdUpdateStatusReportStatusReportId) {
      this.cmdUpdateStatusReportState = 'idle';
      setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'idle');
      this.requestUpdate();
      return;
    }
    if (!this.cmdUpdateStatusReportProjectId) {
      this.cmdUpdateStatusReportState = 'idle';
      setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'idle');
      this.requestUpdate();
      return;
    }
    this.cmdUpdateStatusReportState = 'loading';
    setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'loading');
    this.cmdUpdateStatusReportError = '';
    setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.error', '');
    const params: CmdUpdateStatusReportInput = {
      statusReportId: this.cmdUpdateStatusReportStatusReportId,
      projectId: this.cmdUpdateStatusReportProjectId,
      status: this.cmdUpdateStatusReportStatus,
      title: this.cmdUpdateStatusReportTitle,
      content: this.cmdUpdateStatusReportContent,
      generatedAt: this.cmdUpdateStatusReportGeneratedAt,
      generatedByUserId: this.cmdUpdateStatusReportGeneratedByUserId,
    };
    if (this.cmdUpdateStatusReportCommunicatedRisks) {
      params.communicatedRisks = this.cmdUpdateStatusReportCommunicatedRisks;
    }
    if (this.cmdUpdateStatusReportPublishedAt) {
      params.publishedAt = this.cmdUpdateStatusReportPublishedAt;
    }
    if (this.cmdUpdateStatusReportPublishedByUserId) {
      params.publishedByUserId = this.cmdUpdateStatusReportPublishedByUserId;
    }
    if (this.cmdUpdateStatusReportWithdrawnAt) {
      params.withdrawnAt = this.cmdUpdateStatusReportWithdrawnAt;
    }
    const options: BffClientOptions = { mode: 'blocking' };
    const response = await execBff<CmdUpdateStatusReportOutput>(cmdUpdateStatusReportRoute, params, options);
    if (!response.ok) {
      const errMsg: string = this.readErrorMessage(response.error, 'action.cmdUpdateStatusReport.error');
      this.cmdUpdateStatusReportError = errMsg;
      setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.error', errMsg);
      this.cmdUpdateStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    const data: CmdUpdateStatusReportOutput | null = response.data ?? null;
    this.cmdUpdateStatusReportOutput = data;
    setState('ui.statusReportCatalogue.output.cmdUpdateStatusReport', data);
    try {
      await this.loadQryListStatusReport();
      if (this.qryListStatusReportState === 'error') {
        this.cmdUpdateStatusReportState = 'error';
        setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'error');
        this.requestUpdate();
        return;
      }
    } catch (refreshError: unknown) {
      console.error('cmdUpdateStatusReport refresh failed', refreshError);
      this.cmdUpdateStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    try {
      await this.loadQryProjectPicker();
      if (this.qryProjectPickerState === 'error') {
        this.cmdUpdateStatusReportState = 'error';
        setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'error');
        this.requestUpdate();
        return;
      }
    } catch (refreshError: unknown) {
      console.error('cmdUpdateStatusReport refresh failed', refreshError);
      this.cmdUpdateStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    this.cmdUpdateStatusReportStatusReportId = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.statusReportId', '');
    this.cmdUpdateStatusReportProjectId = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.projectId', '');
    this.cmdUpdateStatusReportStatus = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.status', '');
    this.cmdUpdateStatusReportTitle = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.title', '');
    this.cmdUpdateStatusReportContent = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.content', '');
    this.cmdUpdateStatusReportCommunicatedRisks = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks', '');
    this.cmdUpdateStatusReportGeneratedAt = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt', '');
    this.cmdUpdateStatusReportGeneratedByUserId = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId', '');
    this.cmdUpdateStatusReportPublishedAt = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt', '');
    this.cmdUpdateStatusReportPublishedByUserId = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId', '');
    this.cmdUpdateStatusReportWithdrawnAt = '';
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt', '');
    this.cmdUpdateStatusReportState = 'success';
    setState('ui.statusReportCatalogue.action.cmdUpdateStatusReport.status', 'success');
    this.requestUpdate();
  }

  /** handler for action cmdUpdateStatusReport — bind UI events here */
  handleCmdUpdateStatusReportClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void runBlockingUiAction(async (_signal: AbortSignal) => {
      await this.cmdUpdateStatusReport();
    });
  }

  /** action cmdDeleteStatusReport (command) — route buildFlowFsm.statusReportCatalogue.cmdDeleteStatusReport; inputs: statusReportId; writes ui.statusReportCatalogue.output.cmdDeleteStatusReport; status ui.statusReportCatalogue.action.cmdDeleteStatusReport.status; feedback keys action.cmdDeleteStatusReport.success / action.cmdDeleteStatusReport.error */
  async cmdDeleteStatusReport(): Promise<void> {
    this.syncRouteParams();
    if (!this.cmdDeleteStatusReportStatusReportId) {
      this.cmdDeleteStatusReportState = 'idle';
      setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'idle');
      this.requestUpdate();
      return;
    }
    this.cmdDeleteStatusReportState = 'loading';
    setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'loading');
    this.cmdDeleteStatusReportError = '';
    setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.error', '');
    const params: CmdDeleteStatusReportInput = {
      statusReportId: this.cmdDeleteStatusReportStatusReportId,
    };
    const options: BffClientOptions = { mode: 'blocking' };
    const response = await execBff<CmdDeleteStatusReportOutput>(cmdDeleteStatusReportRoute, params, options);
    if (!response.ok) {
      const errMsg: string = this.readErrorMessage(response.error, 'action.cmdDeleteStatusReport.error');
      this.cmdDeleteStatusReportError = errMsg;
      setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.error', errMsg);
      this.cmdDeleteStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    const data: CmdDeleteStatusReportOutput | null = response.data ?? null;
    this.cmdDeleteStatusReportOutput = data;
    setState('ui.statusReportCatalogue.output.cmdDeleteStatusReport', data);
    try {
      await this.loadQryListStatusReport();
      if (this.qryListStatusReportState === 'error') {
        this.cmdDeleteStatusReportState = 'error';
        setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'error');
        this.requestUpdate();
        return;
      }
    } catch (refreshError: unknown) {
      console.error('cmdDeleteStatusReport refresh failed', refreshError);
      this.cmdDeleteStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    try {
      await this.loadQryProjectPicker();
      if (this.qryProjectPickerState === 'error') {
        this.cmdDeleteStatusReportState = 'error';
        setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'error');
        this.requestUpdate();
        return;
      }
    } catch (refreshError: unknown) {
      console.error('cmdDeleteStatusReport refresh failed', refreshError);
      this.cmdDeleteStatusReportState = 'error';
      setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'error');
      this.requestUpdate();
      return;
    }
    this.cmdDeleteStatusReportStatusReportId = '';
    setState('ui.statusReportCatalogue.input.cmdDeleteStatusReport.statusReportId', '');
    this.cmdDeleteStatusReportState = 'success';
    setState('ui.statusReportCatalogue.action.cmdDeleteStatusReport.status', 'success');
    this.requestUpdate();
  }

  /** handler for action cmdDeleteStatusReport — bind UI events here */
  handleCmdDeleteStatusReportClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void runBlockingUiAction(async (_signal: AbortSignal) => {
      await this.cmdDeleteStatusReport();
    });
  }

  /** action qryProjectPicker (query) — route buildFlowFsm.statusReportCatalogue.qryProjectPicker; inputs: (none); writes ui.statusReportCatalogue.data.qryProjectPicker; status ui.statusReportCatalogue.action.qryProjectPicker.status */
  async loadQryProjectPicker(): Promise<void> {
    this.syncRouteParams();
    this.qryProjectPickerState = 'loading';
    setState('ui.statusReportCatalogue.action.qryProjectPicker.status', 'loading');
    const params: QryProjectPickerInput = {
    };
    const options: BffClientOptions = { mode: 'silent' };
    const response = await execBff<QryProjectPickerOutput[]>(qryProjectPickerRoute, params, options);
    if (response.ok) {
      const data = response.data ?? [];
      this.qryProjectPickerData = data;
      setState('ui.statusReportCatalogue.data.qryProjectPicker', data);
      this.qryProjectPickerState = 'success';
      setState('ui.statusReportCatalogue.action.qryProjectPicker.status', 'success');
    } else {
      this.qryProjectPickerState = 'error';
      setState('ui.statusReportCatalogue.action.qryProjectPicker.status', 'error');
      if (response.error) {
        console.error('qryProjectPicker failed', response.error);
      }
    }
    this.requestUpdate();
  }

  /** handler for action qryProjectPicker — bind UI events here */
  handleQryProjectPickerClick(event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    void this.loadQryProjectPicker();
  }

  /** setter for state ui.statusReportCatalogue.input.cmdCreateStatusReport.projectProjectId */
  setCmdCreateStatusReportProjectProjectId(value: string): void {
    this.cmdCreateStatusReportProjectProjectId = value;
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.projectProjectId', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdCreateStatusReportProjectProjectId — bind UI events here */
  handleCmdCreateStatusReportProjectProjectIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdCreateStatusReportProjectProjectId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdCreateStatusReport.projectExecutionOverviewProjectId */
  setCmdCreateStatusReportProjectExecutionOverviewProjectId(value: string): void {
    this.cmdCreateStatusReportProjectExecutionOverviewProjectId = value;
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.projectExecutionOverviewProjectId', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdCreateStatusReportProjectExecutionOverviewProjectId — bind UI events here */
  handleCmdCreateStatusReportProjectExecutionOverviewProjectIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdCreateStatusReportProjectExecutionOverviewProjectId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdCreateStatusReport.title */
  setCmdCreateStatusReportTitle(value: string): void {
    this.cmdCreateStatusReportTitle = value;
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.title', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdCreateStatusReportTitle — bind UI events here */
  handleCmdCreateStatusReportTitleChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdCreateStatusReportTitle(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdCreateStatusReport.content */
  setCmdCreateStatusReportContent(value: string): void {
    this.cmdCreateStatusReportContent = value;
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.content', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdCreateStatusReportContent — bind UI events here */
  handleCmdCreateStatusReportContentChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdCreateStatusReportContent(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdCreateStatusReport.communicatedRisks */
  setCmdCreateStatusReportCommunicatedRisks(value: string): void {
    this.cmdCreateStatusReportCommunicatedRisks = value;
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.communicatedRisks', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdCreateStatusReportCommunicatedRisks — bind UI events here */
  handleCmdCreateStatusReportCommunicatedRisksChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdCreateStatusReportCommunicatedRisks(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdCreateStatusReport.generatedByUserId */
  setCmdCreateStatusReportGeneratedByUserId(value: string): void {
    this.cmdCreateStatusReportGeneratedByUserId = value;
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.generatedByUserId', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdCreateStatusReportGeneratedByUserId — bind UI events here */
  handleCmdCreateStatusReportGeneratedByUserIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdCreateStatusReportGeneratedByUserId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdCreateStatusReport.publishedByUserId */
  setCmdCreateStatusReportPublishedByUserId(value: string): void {
    this.cmdCreateStatusReportPublishedByUserId = value;
    setState('ui.statusReportCatalogue.input.cmdCreateStatusReport.publishedByUserId', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdCreateStatusReportPublishedByUserId — bind UI events here */
  handleCmdCreateStatusReportPublishedByUserIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdCreateStatusReportPublishedByUserId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.statusReportId */
  setCmdUpdateStatusReportStatusReportId(value: string): void {
    this.cmdUpdateStatusReportStatusReportId = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.statusReportId', value);
    const collection =
      (getState('ui.statusReportCatalogue.data.qryListStatusReport') as QryListStatusReportOutput[] | null | undefined) ?? this.qryListStatusReportData;
    if (Array.isArray(collection) && collection.length > 0) {
      const item = collection.find(
        (row: QryListStatusReportOutput) => String(row.statusReportId) === String(value),
      );
      if (item) {
        this.cmdUpdateStatusReportStatus = item.status;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.status', item.status);
        this.cmdUpdateStatusReportTitle = item.title;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.title', item.title);
        this.cmdUpdateStatusReportContent = item.content;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.content', item.content);
        this.cmdUpdateStatusReportCommunicatedRisks = item.communicatedRisks;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks', item.communicatedRisks);
        this.cmdUpdateStatusReportGeneratedAt = item.generatedAt;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt', item.generatedAt);
        this.cmdUpdateStatusReportGeneratedByUserId = item.generatedByUserId;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId', item.generatedByUserId);
        this.cmdUpdateStatusReportPublishedAt = item.publishedAt;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt', item.publishedAt);
        this.cmdUpdateStatusReportPublishedByUserId = item.publishedByUserId;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId', item.publishedByUserId);
        this.cmdUpdateStatusReportWithdrawnAt = item.withdrawnAt;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt', item.withdrawnAt);
      }
    }
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportStatusReportId — bind UI events here */
  handleCmdUpdateStatusReportStatusReportIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportStatusReportId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.projectId */
  setCmdUpdateStatusReportProjectId(value: string): void {
    this.cmdUpdateStatusReportProjectId = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.projectId', value);
    const collection =
      (getState('ui.statusReportCatalogue.data.qryListStatusReport') as QryListStatusReportOutput[] | null | undefined) ?? this.qryListStatusReportData;
    if (Array.isArray(collection) && collection.length > 0) {
      const item = collection.find(
        (row: QryListStatusReportOutput) => String(row.projectId) === String(value),
      );
      if (item) {
        this.cmdUpdateStatusReportStatus = item.status;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.status', item.status);
        this.cmdUpdateStatusReportTitle = item.title;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.title', item.title);
        this.cmdUpdateStatusReportContent = item.content;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.content', item.content);
        this.cmdUpdateStatusReportCommunicatedRisks = item.communicatedRisks;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks', item.communicatedRisks);
        this.cmdUpdateStatusReportGeneratedAt = item.generatedAt;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt', item.generatedAt);
        this.cmdUpdateStatusReportGeneratedByUserId = item.generatedByUserId;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId', item.generatedByUserId);
        this.cmdUpdateStatusReportPublishedAt = item.publishedAt;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt', item.publishedAt);
        this.cmdUpdateStatusReportPublishedByUserId = item.publishedByUserId;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId', item.publishedByUserId);
        this.cmdUpdateStatusReportWithdrawnAt = item.withdrawnAt;
        setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt', item.withdrawnAt);
      }
    }
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportProjectId — bind UI events here */
  handleCmdUpdateStatusReportProjectIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportProjectId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.status */
  setCmdUpdateStatusReportStatus(value: string): void {
    this.cmdUpdateStatusReportStatus = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.status', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportStatus — bind UI events here */
  handleCmdUpdateStatusReportStatusChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportStatus(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.title */
  setCmdUpdateStatusReportTitle(value: string): void {
    this.cmdUpdateStatusReportTitle = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.title', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportTitle — bind UI events here */
  handleCmdUpdateStatusReportTitleChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportTitle(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.content */
  setCmdUpdateStatusReportContent(value: string): void {
    this.cmdUpdateStatusReportContent = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.content', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportContent — bind UI events here */
  handleCmdUpdateStatusReportContentChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportContent(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks */
  setCmdUpdateStatusReportCommunicatedRisks(value: string): void {
    this.cmdUpdateStatusReportCommunicatedRisks = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.communicatedRisks', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportCommunicatedRisks — bind UI events here */
  handleCmdUpdateStatusReportCommunicatedRisksChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportCommunicatedRisks(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt */
  setCmdUpdateStatusReportGeneratedAt(value: string): void {
    this.cmdUpdateStatusReportGeneratedAt = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedAt', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportGeneratedAt — bind UI events here */
  handleCmdUpdateStatusReportGeneratedAtChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportGeneratedAt(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId */
  setCmdUpdateStatusReportGeneratedByUserId(value: string): void {
    this.cmdUpdateStatusReportGeneratedByUserId = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.generatedByUserId', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportGeneratedByUserId — bind UI events here */
  handleCmdUpdateStatusReportGeneratedByUserIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportGeneratedByUserId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt */
  setCmdUpdateStatusReportPublishedAt(value: string): void {
    this.cmdUpdateStatusReportPublishedAt = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedAt', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportPublishedAt — bind UI events here */
  handleCmdUpdateStatusReportPublishedAtChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportPublishedAt(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId */
  setCmdUpdateStatusReportPublishedByUserId(value: string): void {
    this.cmdUpdateStatusReportPublishedByUserId = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.publishedByUserId', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportPublishedByUserId — bind UI events here */
  handleCmdUpdateStatusReportPublishedByUserIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportPublishedByUserId(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt */
  setCmdUpdateStatusReportWithdrawnAt(value: string): void {
    this.cmdUpdateStatusReportWithdrawnAt = value;
    setState('ui.statusReportCatalogue.input.cmdUpdateStatusReport.withdrawnAt', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdUpdateStatusReportWithdrawnAt — bind UI events here */
  handleCmdUpdateStatusReportWithdrawnAtChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdUpdateStatusReportWithdrawnAt(value);
  }

  /** setter for state ui.statusReportCatalogue.input.cmdDeleteStatusReport.statusReportId */
  setCmdDeleteStatusReportStatusReportId(value: string): void {
    this.cmdDeleteStatusReportStatusReportId = value;
    setState('ui.statusReportCatalogue.input.cmdDeleteStatusReport.statusReportId', value);
    this.requestUpdate();
  }

  /** handler for action set.cmdDeleteStatusReportStatusReportId — bind UI events here */
  handleCmdDeleteStatusReportStatusReportIdChange(event: Event): void {
    const target = event.target as HTMLInputElement | HTMLSelectElement | null;
    const value: string = target && 'value' in target ? String(target.value) : '';
    this.setCmdDeleteStatusReportStatusReportId(value);
  }
}
