/// <mls fileReference="_102046_/l2/buildFlowFsm/web/shared/statusReportCatalogue.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { BuildFlowFsmStatusReportCatalogueBase } from '/_102046_/l2/buildFlowFsm/web/shared/statusReportCatalogue.js';
import type { CmdCreateStatusReportInput, CmdCreateStatusReportOutput, CmdDeleteStatusReportInput, CmdDeleteStatusReportOutput, CmdUpdateStatusReportInput, CmdUpdateStatusReportOutput, QryListStatusReportOutput, QryProjectPickerOutput } from '/_102046_/l2/buildFlowFsm/web/contracts/statusReportCatalogue.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: BuildFlowFsmStatusReportCatalogueBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_qryListStatusReportState = Assert<Assignable<typeof page.qryListStatusReportState, "idle" | "loading" | "success" | "error">>;
type _State_qryListStatusReportData = Assert<Assignable<typeof page.qryListStatusReportData, unknown[] | QryListStatusReportOutput>>;
type _State_cmdCreateStatusReportState = Assert<Assignable<typeof page.cmdCreateStatusReportState, "idle" | "loading" | "success" | "error">>;
type _State_cmdCreateStatusReportProjectProjectId = Assert<Assignable<typeof page.cmdCreateStatusReportProjectProjectId, string | CmdCreateStatusReportInput["projectProjectId"]>>;
type _State_cmdCreateStatusReportProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.cmdCreateStatusReportProjectExecutionOverviewProjectId, string | CmdCreateStatusReportInput["projectExecutionOverviewProjectId"]>>;
type _State_cmdCreateStatusReportTitle = Assert<Assignable<typeof page.cmdCreateStatusReportTitle, string | CmdCreateStatusReportInput["title"]>>;
type _State_cmdCreateStatusReportContent = Assert<Assignable<typeof page.cmdCreateStatusReportContent, string | CmdCreateStatusReportInput["content"]>>;
type _State_cmdCreateStatusReportCommunicatedRisks = Assert<Assignable<typeof page.cmdCreateStatusReportCommunicatedRisks, string | CmdCreateStatusReportInput["communicatedRisks"]>>;
type _State_cmdCreateStatusReportGeneratedByUserId = Assert<Assignable<typeof page.cmdCreateStatusReportGeneratedByUserId, string | CmdCreateStatusReportInput["generatedByUserId"]>>;
type _State_cmdCreateStatusReportPublishedByUserId = Assert<Assignable<typeof page.cmdCreateStatusReportPublishedByUserId, string | CmdCreateStatusReportInput["publishedByUserId"]>>;
type _State_cmdCreateStatusReportOutput = Assert<Assignable<typeof page.cmdCreateStatusReportOutput, CmdCreateStatusReportOutput | null>>;
type _State_cmdCreateStatusReportError = Assert<Assignable<typeof page.cmdCreateStatusReportError, string>>;
type _State_cmdUpdateStatusReportState = Assert<Assignable<typeof page.cmdUpdateStatusReportState, "idle" | "loading" | "success" | "error">>;
type _State_cmdUpdateStatusReportStatusReportId = Assert<Assignable<typeof page.cmdUpdateStatusReportStatusReportId, string | CmdUpdateStatusReportInput["statusReportId"]>>;
type _State_cmdUpdateStatusReportProjectId = Assert<Assignable<typeof page.cmdUpdateStatusReportProjectId, string | CmdUpdateStatusReportInput["projectId"]>>;
type _State_cmdUpdateStatusReportStatus = Assert<Assignable<typeof page.cmdUpdateStatusReportStatus, string | CmdUpdateStatusReportInput["status"]>>;
type _State_cmdUpdateStatusReportTitle = Assert<Assignable<typeof page.cmdUpdateStatusReportTitle, string | CmdUpdateStatusReportInput["title"]>>;
type _State_cmdUpdateStatusReportContent = Assert<Assignable<typeof page.cmdUpdateStatusReportContent, string | CmdUpdateStatusReportInput["content"]>>;
type _State_cmdUpdateStatusReportCommunicatedRisks = Assert<Assignable<typeof page.cmdUpdateStatusReportCommunicatedRisks, string | CmdUpdateStatusReportInput["communicatedRisks"]>>;
type _State_cmdUpdateStatusReportGeneratedAt = Assert<Assignable<typeof page.cmdUpdateStatusReportGeneratedAt, string | CmdUpdateStatusReportInput["generatedAt"]>>;
type _State_cmdUpdateStatusReportGeneratedByUserId = Assert<Assignable<typeof page.cmdUpdateStatusReportGeneratedByUserId, string | CmdUpdateStatusReportInput["generatedByUserId"]>>;
type _State_cmdUpdateStatusReportPublishedAt = Assert<Assignable<typeof page.cmdUpdateStatusReportPublishedAt, string | CmdUpdateStatusReportInput["publishedAt"]>>;
type _State_cmdUpdateStatusReportPublishedByUserId = Assert<Assignable<typeof page.cmdUpdateStatusReportPublishedByUserId, string | CmdUpdateStatusReportInput["publishedByUserId"]>>;
type _State_cmdUpdateStatusReportWithdrawnAt = Assert<Assignable<typeof page.cmdUpdateStatusReportWithdrawnAt, string | CmdUpdateStatusReportInput["withdrawnAt"]>>;
type _State_cmdUpdateStatusReportOutput = Assert<Assignable<typeof page.cmdUpdateStatusReportOutput, CmdUpdateStatusReportOutput | null>>;
type _State_cmdUpdateStatusReportError = Assert<Assignable<typeof page.cmdUpdateStatusReportError, string>>;
type _State_cmdDeleteStatusReportState = Assert<Assignable<typeof page.cmdDeleteStatusReportState, "idle" | "loading" | "success" | "error">>;
type _State_cmdDeleteStatusReportStatusReportId = Assert<Assignable<typeof page.cmdDeleteStatusReportStatusReportId, string | CmdDeleteStatusReportInput["statusReportId"]>>;
type _State_cmdDeleteStatusReportOutput = Assert<Assignable<typeof page.cmdDeleteStatusReportOutput, CmdDeleteStatusReportOutput | null>>;
type _State_cmdDeleteStatusReportError = Assert<Assignable<typeof page.cmdDeleteStatusReportError, string>>;
type _State_qryProjectPickerState = Assert<Assignable<typeof page.qryProjectPickerState, "idle" | "loading" | "success" | "error">>;
type _State_qryProjectPickerData = Assert<Assignable<typeof page.qryProjectPickerData, unknown[] | QryProjectPickerOutput>>;
type _Action_loadQryListStatusReport = Assert<Assignable<typeof page.loadQryListStatusReport, (...args: any[]) => unknown>>;
type _Handler_handleQryListStatusReportClick = Assert<Assignable<typeof page.handleQryListStatusReportClick, (...args: any[]) => unknown>>;
type _Action_cmdCreateStatusReport = Assert<Assignable<typeof page.cmdCreateStatusReport, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportClick = Assert<Assignable<typeof page.handleCmdCreateStatusReportClick, (...args: any[]) => unknown>>;
type _Action_cmdUpdateStatusReport = Assert<Assignable<typeof page.cmdUpdateStatusReport, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportClick = Assert<Assignable<typeof page.handleCmdUpdateStatusReportClick, (...args: any[]) => unknown>>;
type _Action_cmdDeleteStatusReport = Assert<Assignable<typeof page.cmdDeleteStatusReport, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteStatusReportClick = Assert<Assignable<typeof page.handleCmdDeleteStatusReportClick, (...args: any[]) => unknown>>;
type _Action_loadQryProjectPicker = Assert<Assignable<typeof page.loadQryProjectPicker, (...args: any[]) => unknown>>;
type _Handler_handleQryProjectPickerClick = Assert<Assignable<typeof page.handleQryProjectPickerClick, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportProjectProjectId = Assert<Assignable<typeof page.setCmdCreateStatusReportProjectProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportProjectProjectIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportProjectProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportProjectExecutionOverviewProjectId = Assert<Assignable<typeof page.setCmdCreateStatusReportProjectExecutionOverviewProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportProjectExecutionOverviewProjectIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportProjectExecutionOverviewProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportTitle = Assert<Assignable<typeof page.setCmdCreateStatusReportTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportTitleChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportContent = Assert<Assignable<typeof page.setCmdCreateStatusReportContent, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportContentChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportContentChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportCommunicatedRisks = Assert<Assignable<typeof page.setCmdCreateStatusReportCommunicatedRisks, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportCommunicatedRisksChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportCommunicatedRisksChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportGeneratedByUserId = Assert<Assignable<typeof page.setCmdCreateStatusReportGeneratedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportGeneratedByUserIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportGeneratedByUserIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateStatusReportPublishedByUserId = Assert<Assignable<typeof page.setCmdCreateStatusReportPublishedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateStatusReportPublishedByUserIdChange = Assert<Assignable<typeof page.handleCmdCreateStatusReportPublishedByUserIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportStatusReportId = Assert<Assignable<typeof page.setCmdUpdateStatusReportStatusReportId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportStatusReportIdChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportStatusReportIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportProjectId = Assert<Assignable<typeof page.setCmdUpdateStatusReportProjectId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportProjectIdChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportProjectIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportStatus = Assert<Assignable<typeof page.setCmdUpdateStatusReportStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportStatusChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportTitle = Assert<Assignable<typeof page.setCmdUpdateStatusReportTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportTitleChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportContent = Assert<Assignable<typeof page.setCmdUpdateStatusReportContent, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportContentChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportContentChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportCommunicatedRisks = Assert<Assignable<typeof page.setCmdUpdateStatusReportCommunicatedRisks, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportCommunicatedRisksChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportCommunicatedRisksChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportGeneratedAt = Assert<Assignable<typeof page.setCmdUpdateStatusReportGeneratedAt, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportGeneratedAtChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportGeneratedAtChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportGeneratedByUserId = Assert<Assignable<typeof page.setCmdUpdateStatusReportGeneratedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportGeneratedByUserIdChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportGeneratedByUserIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportPublishedAt = Assert<Assignable<typeof page.setCmdUpdateStatusReportPublishedAt, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportPublishedAtChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportPublishedAtChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportPublishedByUserId = Assert<Assignable<typeof page.setCmdUpdateStatusReportPublishedByUserId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportPublishedByUserIdChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportPublishedByUserIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateStatusReportWithdrawnAt = Assert<Assignable<typeof page.setCmdUpdateStatusReportWithdrawnAt, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateStatusReportWithdrawnAtChange = Assert<Assignable<typeof page.handleCmdUpdateStatusReportWithdrawnAtChange, (...args: any[]) => unknown>>;
type _Action_setCmdDeleteStatusReportStatusReportId = Assert<Assignable<typeof page.setCmdDeleteStatusReportStatusReportId, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteStatusReportStatusReportIdChange = Assert<Assignable<typeof page.handleCmdDeleteStatusReportStatusReportIdChange, (...args: any[]) => unknown>>;

export {};